### ISSUE TITLE
what about jsonb?

### ISSUE THREAD

**Issue by borisaka** [tminglei/slick-pg#122]
I've tried to use slick-pg with jsonb coulmn, but it fails with
```
You will need to rewrite or cast the expression.
  at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2161)
  at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1890)
  at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
  at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:560)
  at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
  at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:363)
  at com.jolbox.bonecp.PreparedStatementHandle.executeUpdate(PreparedStatementHandle.java:205)
  at scala.slick.driver.JdbcInvokerComponent$UpdateInvoker$$anonfun$update$1.apply(JdbcInvokerComponent.scala:88)
  at scala.slick.driver.JdbcInvokerComponent$UpdateInvoker$$anonfun$update$1.apply(JdbcInvokerComponent.scala:84)
  at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:191)
  at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:389)
  at scala.slick.driver.JdbcInvokerComponent$UpdateInvoker.update(JdbcInvokerComponent.scala:84)
```
I've tried to add  O.DBType("JSONB") to scala code, but it workless.
I am newbe in slick and i haven't any sugguestions about what to do

**Comment by tminglei** [comment]
Hi @borisaka I just released `slick-pg` v0.8.1, which includes new added jsonb support.
Pls try again, and any question pls let me know.

**Comment by borisaka** [comment]
Thanks, @tminglei  it perfectly works! 
A little question - is it possible (or planned to be possible) to type some colums as json, and some another - as jsonb?

**Comment by tminglei** [comment]
Hi @borisaka you can declare mixed pg types of json and jsonb, but not simply using O.DBType("JSON")/O.DBType("JSONB").
Because it's not easy to dynamically extract pg type from column instance.

Instead, you should define another json type mapper, which bind to the pg json type and another scala type. Then when you use the new scala type to declare column, you got you want.

_This is not convenient, but I haven't a simple solution to resolve it._
