### ISSUE TITLE
Classpath error - java.lang.NoSuchMethodError: org.json4s.JsonMethods.render

### ISSUE THREAD

**Issue by arjunjun4u** [tminglei/slick-pg#138]
Hi, 

I was trying to use the PgJson4sSupport  example from https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/addon/PgJson4sSupportTest.scala 

And I am getting the following error. I believe this has got to do with some classpath issue (with a version mismatch possibly)?

```
java.lang.NoSuchMethodError: org.json4s.JsonMethods.render(Lorg/json4s/JsonAST$JValue;)Ljava/lang/Object;
	at com.github.tminglei.slickpg.PgJson4sSupport$Json4sJsonImplicits$$anonfun$2.apply(PgJson4sSupport.scala:23)
	at com.github.tminglei.slickpg.PgJson4sSupport$Json4sJsonImplicits$$anonfun$2.apply(PgJson4sSupport.scala:23)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.mkPgObject(PgCommonJdbcTypes.scala:30)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.setValue(PgCommonJdbcTypes.scala:23)
	at scala.slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:19)
	at scala.slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:11)
[ERROR] [03/15/2015 03:13:50.158] [on-spray-can-akka.actor.default-dispatcher-4] [ActorSystem(on-spray-can)] Uncaught error from thread [on-spray-can-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: org.json4s.JsonMethods.render(Lorg/json4s/JsonAST$JValue;)Ljava/lang/Object;
	at com.github.tminglei.slickpg.PgJson4sSupport$Json4sJsonImplicits$$anonfun$2.apply(PgJson4sSupport.scala:23)
	at com.github.tminglei.slickpg.PgJson4sSupport$Json4sJsonImplicits$$anonfun$2.apply(PgJson4sSupport.scala:23)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.mkPgObject(PgCommonJdbcTypes.scala:30)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.setValue(PgCommonJdbcTypes.scala:23)
```
Not sure if it is under your scope, but I think you might find the following links relevant.
1. https://github.com/json4s/json4s/issues/147
2. http://stackoverflow.com/questions/24877062/receiving-bad-symbolic-reference-to-org-json4s-jsonast-in-eclipse-scala-ide (suggesting you add  your dependency  "org.json4s"    %% "json4s-ast"   % "3.2.11")

Any help would be much appreciated.

Thanks

**Comment by arjunjun4u** [comment]
For more context,

```
trait MyPostgresDriver extends PostgresDriver with PgArraySupport with PgHStoreSupport with PgJson4sSupport {
  
  override lazy val Implicit = new ImplicitsPlus {}
  override val simple = new SimpleQLPlus {}
  
  override val pgjson = "jsonb"
  type DOCType = text.Document
  override val jsonMethods = org.json4s.native.JsonMethods

  trait ImplicitsPlus extends Implicits
    with ArrayImplicits
    with HStoreImplicits
    with JsonImplicits
    with Json4sJsonPlainImplicits
  
  trait SimpleQLPlus extends SimpleQL
    with ImplicitsPlus

}

object MyPostgresDriver extends MyPostgresDriver
```

**Comment by tminglei** [comment]
Hi @arjunjun4u, which `json4s` and `slick-pg` versions are you using?
Because there's a binary incompatibility in the render() method between json4s 3.2.10 and 3.2.11 json4s/json4s#212.

_We have encountered the problem in #134._

**Comment by arjunjun4u** [comment]
Hi @tminglei 

I am getting a different issue now.

You were right about it the version mismatch. slick-pg 0.8.2 works fine with json4s 3.2.10 and likewise 0.8.3 with 3.2.11. But the new issue comes up in both combinations

With
```
def json = column[JValue]("json")
```
I get following error in postgres logs
```
2015-03-15 16:54:55 IST DEBUG:  CommitTransactionCommand
2015-03-15 16:54:55 IST DEBUG:  parse <unnamed>: create table "JsonTest1" ("id" SERIAL NOT NULL PRIMARY KEY,"json" null NOT NULL)
2015-03-15 16:54:55 IST DEBUG:  StartTransactionCommand
2015-03-15 16:54:55 IST ERROR:  syntax error at or near "null" at character 67
2015-03-15 16:54:55 IST STATEMENT:  create table "JsonTest1" ("id" SERIAL NOT NULL PRIMARY KEY,"json" null NOT NULL)
```

And when I use either of the following to define the dbtype 
```
def json = column[JValue]("json", O.DBType("json"))
```
or 
```
def json = column[JValue]("json", O.DBType("json"), O.Nullable)
```
I get 
```
2015-03-15 17:04:42 IST STATEMENT:  SELECT pg_type.oid   FROM pg_catalog.pg_type   LEFT   JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE typname = $1  ORDER BY sp.r, pg_type.oid DESC LIMIT 1
2015-03-15 17:04:42 IST DEBUG:  bind <unnamed> to <unnamed>
2015-03-15 17:04:42 IST LOG:  execute <unnamed>: SELECT pg_type.oid   FROM pg_catalog.pg_type   LEFT   JOIN (select ns.oid as nspoid, ns.nspname, r.r           from pg_namespace as ns           join ( select s.r, (current_schemas(false))[s.r] as nspname                    from generate_series(1, array_upper(current_schemas(false), 1)) as s(r) ) as r          using ( nspname )        ) as sp     ON sp.nspoid = typnamespace  WHERE typname = $1  ORDER BY sp.r, pg_type.oid DESC LIMIT 1
2015-03-15 17:04:42 IST DETAIL:  parameters: $1 = NULL
```
All I can understand from the logs is that typname = $1, which is being NULL here. 
And the table does get created 
```
CREATE TABLE "JsonTest1"
(
  id serial NOT NULL,
  json json NOT NULL,
  CONSTRAINT "JsonTest1_pkey" PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
```
Also, I had to mention the explicit dbtype even before the version mismatch issue.

Any idea, what might be issue?

Thanks

**Comment by arjunjun4u** [comment]
Missed the exception stack
```
[ERROR] [03/15/2015 17:39:20.626] [on-spray-can-akka.actor.default-dispatcher-4] [akka://on-spray-can/user/api-service] Unknown type null.
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
	at akka.actor.ActorCell.create(ActorCell.scala:596)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.postgresql.util.PSQLException: Unknown type null.
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setPGobject(AbstractJdbc2Statement.java:1703)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setObject(AbstractJdbc2Statement.java:1926)
	at org.postgresql.jdbc3g.AbstractJdbc3gStatement.setObject(AbstractJdbc3gStatement.java:36)
	at org.postgresql.jdbc4.AbstractJdbc4Statement.setObject(AbstractJdbc4Statement.java:48)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.setValue(PgCommonJdbcTypes.scala:23)
	at scala.slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:19)
	at scala.slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:11)
	at scala.slick.relational.ProductResultConverter.set(ResultConverter.scala:71)
	at scala.slick.relational.ProductResultConverter.set(ResultConverter.scala:46)
	at scala.slick.relational.TypeMappingResultConverter.set(ResultConverter.scala:127)
	at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$internalInsert$1.apply(JdbcInsertInvokerComponent.scala:182)
	at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$internalInsert$1.apply(JdbcInsertInvokerComponent.scala:180)
	at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:191)
	at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:389)
	at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.preparedInsert(JdbcInsertInvokerComponent.scala:170)
	at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.internalInsert(JdbcInsertInvokerComponent.scala:180)
	at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.insert(JdbcInsertInvokerComponent.scala:175)

```

**Comment by tminglei** [comment]
Hi @arjunjun4u, it's strange to me.
But if you declared a `jsonb` type in postgres 9.3, this is possible.

_p.s. you can only declare a `jsonb` in postgres 9.4 currently._

**Comment by arjunjun4u** [comment]
Hi @tminglei,

For some weird reason not setting the pgjson value worked in postgres 9.4
```
// override val pgjson = "jsonb"
```

Thanks for your help all along and inadvertently fixing my latter issue.

**Comment by tminglei** [comment]
Glad to hear that. _You're welcome! :)_

**Comment by amullins** [comment]
#134 
It looks like v0.8.3 is the only version that uses json4s 3.2.11. More recent releases are using json4s v3.2.10.

**Comment by tminglei** [comment]
@amullins, yes, seems json4s 3.2.11 is the only version they made the mistake.

_Did you also encounter a same problem like #134, that is, you have to use json4s 3.2.11?_

**Comment by amullins** [comment]
Yes, I have another dependency using v3.2.11. I reverted back to slick-pg v0.8.3 to resolve this issue, for now. I didn't realize it was an issue with json4s. Looks like json4s/json4s#212 is the ticket I should be following...

**Comment by tminglei** [comment]
Ok. 
_BTW, if necessary, I can also release a version for json4s 3.2.11 again._

**Comment by t3chnoboy** [comment]
> BTW, if necessary, I can also release a version for json4s 3.2.11 again.

@tminglei yes please! 🙏 
that would be really-really great!

**Comment by tminglei** [comment]
@t3chnoboy can you try to upgrade latest json4s?

As I know, the wrongly change to method `JsonMethods.render` in json4s v3.2.11, was officially published in later feature releases.

**Comment by t3chnoboy** [comment]
@tminglei unfortunately we can't easily upgrade json4s to `3.3.0`.
They've bumped `jackson`  in `3.3.0` https://github.com/json4s/json4s/pull/304  and that change is incompatible with our `finatra` version 😞

**Comment by tminglei** [comment]
@t3chnoboy just released a special version for json4s v3.2.11.

You can use it by add dependency
```scala
libraryDependencies += "com.github.tminglei" %% "slick-pg_json4s" % "0.14.5_json4s-3.2.11"
```

_p.s. only dependency for json4s addon need update, other dependencies keep unchanged and you'd better upgrade to slick-pg v0.14.5._

**Comment by t3chnoboy** [comment]
Hi @tminglei! Thanks for publishing! 😊 
But there's a problem. I think we have to stick with `sick-pg 0.8.x` because we are stuck with `slick 2.1.0`.
Is it possible to make `slick-pg` work with `slick 2.1.0` and `jackson 3.2.11`?

**Comment by tminglei** [comment]
I thought that you can do it yourself. But, ok, there is another special version for json4s v3.2.11. :-)

pls update your dependency as below to use it:
```scala
libraryDependencies += "com.github.tminglei" %% "slick-pg_json4s" % "0.8.5_json4s-3.2.11"
```

**Comment by t3chnoboy** [comment]
Thank you @tminglei! It worked! 🙌 

However, it looks like you published:
```scala
"com.github.tminglei" %% "slick-pg" % "0.8.5_json4s-3.2.11"
```
not 
```scala
"com.github.tminglei" %% "slick-pg_json4s" % "0.8.5_json4s-3.2.11"
```

**Comment by tminglei** [comment]
Yes, it should be `"com.github.tminglei" %% "slick-pg" % "0.8.5_json4s-3.2.11"`.
It's still an all-in-one jar for 0.8.x.
