### ISSUE TITLE
Enable Seq[JsValue] mapping (once again)

### ISSUE THREAD

**Issue by akagroundhog** [tminglei/slick-pg#149]
Hi! Thanks for the great project, slick-pg helps a lot! However, some issues happen.

I'm trying to store `jsonb[]` in Postgres DB and map it to `Seq[JsValue]` in my project via slick-pg 0.9.0-beta. I know about the problem in the Postgres JDBC driver, and I'm trying to use a workaround described in [issue #84 "Enable List[JsValue] mapping"](https://github.com/tminglei/slick-pg/issues/84#issuecomment-57912524). The workaround was written for version 0.6.5.2, so I've changed it a bit according to the example in [PgArraySupportTest.scala](https://github.com/tminglei/slick-pg/blob/v0.9.0-beta/src/test/scala/com/github/tminglei/slickpg/PgArraySupportTest.scala#L22) and deprecation messages in [PgArrayJdbcTypes.scala](https://github.com/tminglei/slick-pg/blob/v0.9.0-beta/core/src/main/scala/com/github/tminglei/slickpg/array/PgArrayJdbcTypes.scala#L71). Essentially, my mapper is defined like this:

```scala
trait MyArrayImplicits {
  implicit val jsValueListTypeMapper = new AdvancedArrayJdbcType[JsValue]("jsonb",
    fromString[JsValue](Json.parse)(_).orNull, mkString[JsValue](Json.stringify)(_)).to(_.toSeq)
}
```

The project compiles fine, but in runtime I'm getting an Execution exception:

```
play.api.Application$$anon$1: Execution exception[[NoSuchElementException: head of empty list]]
        at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
        at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:205) [play_2.11-2.3.8.jar:2.3.8]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$14$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:202) [play_2.11-2.3.8.jar:2.3.8]
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.6.jar:na]
Caused by: java.util.NoSuchElementException: head of empty list
        at scala.collection.immutable.Nil$.head(List.scala:420) ~[scala-library-2.11.6.jar:na]
        at scala.collection.immutable.Nil$.head(List.scala:417) ~[scala-library-2.11.6.jar:na]
        at scala.collection.mutable.Stack.top(Stack.scala:132) ~[scala-library-2.11.6.jar:na]
        at com.github.tminglei.slickpg.utils.PgTokenHelper$$anonfun$grouping$1$$anonfun$apply$3.apply(PgTokenHelper.scala:255) ~[slick-pg_core_2.11-0.9.0-beta.jar:0.9.0-beta]
        at com.github.tminglei.slickpg.utils.PgTokenHelper$$anonfun$grouping$1$$anonfun$apply$3.apply(PgTokenHelper.scala:249) ~[slick-pg_core_2.11-0.9.0-beta.jar:0.9.0-beta]
```

It seems like at some point the `stack` is empty. I tried to fix it myself to submit a pull request, but things seems too complicated for me. Am I missing something or there is an issue in version 0.9.0-beta? If that, could you please fix it? There once was a working solution, and it would be nice to have it again.

**Comment by tminglei** [comment]
Hi @akagroundhog, I just supplemented some test cases for json[], and they look fine.

For your case, the `.to(_.toSeq)` is not necessary, but it should be ok.
And except that, I can't find any other problem.

_Maybe you can check other cause or provide more details to help analyze._

**Comment by akagroundhog** [comment]
Hi, thanks for the test cases, but my problem is still there. I will provide more details in the next few days. My project is a bit complex so I want to cut off some details and see if the problem persists (and maybe to provide some test cases).

**Comment by akagroundhog** [comment]
I switched to JsArray in my project, and it seems like my "next few days" lasts a little longer than I expected. I'll reopen this issue if I encounter such problem again in the next few, let's say, months.

**Comment by driquelme** [comment]
Hi, I'm also having this problem.
I have tested with the following json string: 
```
{"{\"level\":\"DAILY_LEVEL\",\"start\":{\"year\":2013,\"month\":1,\"day\":1},\"end\":{\"year\":2016,\"month\":1,\"day\":1}}"}
```
I am attaching a screenshot of the debug session.
<img width="699" alt="captura de pantalla 2015-10-12 a las 1 33 30 p m" src="https://cloud.githubusercontent.com/assets/5178158/10433147/38c0b608-70e6-11e5-8c7c-b97ca2e43770.png">
<img width="663" alt="captura de pantalla 2015-10-12 a las 1 32 59 p m" src="https://cloud.githubusercontent.com/assets/5178158/10433152/3f66d014-70e6-11e5-9d00-65ce24f33cb4.png">

The relevant stack trace:
```
Caused by: java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:420)
	at scala.collection.immutable.Nil$.head(List.scala:417)
	at scala.collection.mutable.Stack.top(Stack.scala:132)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$$anonfun$grouping$1$$anonfun$apply$3.apply(PgTokenHelper.scala:264)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$$anonfun$grouping$1$$anonfun$apply$3.apply(PgTokenHelper.scala:258)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$$anonfun$grouping$1.apply(PgTokenHelper.scala:258)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$$anonfun$grouping$1.apply(PgTokenHelper.scala:165)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.grouping(PgTokenHelper.scala:165)
	at com.github.tminglei.slickpg.utils.SimpleArrayUtils$.fromString(SimpleArrayUtils.scala:11)
	at org.driquelme.tableagg.MyPostgresDriver$MyAPI$$anonfun$2.apply(MyPostgresDriver.scala:28)
	at org.driquelme.tableagg.MyPostgresDriver$MyAPI$$anonfun$2.apply(MyPostgresDriver.scala:28)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$AdvancedArrayJdbcType.getValue(PgArrayJdbcTypes.scala:93)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$AdvancedArrayJdbcType.getValue(PgArrayJdbcTypes.scala:81)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.getValue(PgArrayJdbcTypes.scala:119)

```

**Comment by tminglei** [comment]
Thanks for reporting it. I'll check it.

**Comment by tminglei** [comment]
Hi @driquelme, fixed, pls help check. _Thanks! :+1:_

**Comment by driquelme** [comment]
Great !, will do.

Daniel Riquelme
CTO Cloudintelligence SpA
daniel@cloudintelligence.cl

**Comment by driquelme** [comment]
Hi, I'm still getting the same error.
The screenshot shows the debugger at the point of failure.
In the variables below you can see that the stack has size 0.

<img width="678" alt="captura de pantalla 2015-10-17 a las 7 51 34 p m" src="https://cloud.githubusercontent.com/assets/5178158/10561624/fa0187be-7507-11e5-8105-f5d0ce59762e.png">

**Comment by tminglei** [comment]
Well, the changes weren't released, you used the snapshot jar you built yourself?

**Comment by driquelme** [comment]
Yes I did, you can check that my snapshot shows the code you added in the fix
https://github.com/tminglei/slick-pg/commit/0026a87cf6ea7adb6884be1877b97581f173ffe0

**Comment by tminglei** [comment]
Oh, yes, I saw it.

Can you paste the codes that you're reproducing it?

**Comment by driquelme** [comment]
Let me double check. I did not change the build to the snapshot version, just did a simple publish-local for the same version and as I recall the releases are not re-published by sbt when you do a publish-local.

**Comment by tminglei** [comment]
Ok, thanks!

**Comment by driquelme** [comment]
It works !

**Comment by tminglei** [comment]
Glad to hear that! :-)
