### ISSUE TITLE
[warn] >>> DUPLICATED converter for Short!!!  If it's expected, pls ignore it.

### ISSUE THREAD

**Issue by sundriver** [tminglei/slick-pg#195]
Hi,
 I am receiving the following message in play log files, is this something to worry about ? I am using pg-slick 0.9.2. 

Here is the stacktrace, just in case :
```
java.lang.RuntimeException: [warn] >>> DUPLICATED converter for Short!!!  If it's expected, pls ignore it.
	at com.github.tminglei.slickpg.utils.PlainSQLUtils$.addNextArrayConverter(PlainSQLUtils.scala:15)
	at com.github.tminglei.slickpg.PgArraySupport$SimpleArrayPlainImplicits$class.$init$(PgArraySupport.scala:44)
	at common.MyPostgresDriver$$anon$1.<init>(MyPostgresDriver.scala:14)
	at common.MyPostgresDriver$class.$init$(MyPostgresDriver.scala:14)
	at common.MyPostgresDriver$.<init>(MyPostgresDriver.scala:33)
	at common.MyPostgresDriver$.<clinit>(MyPostgresDriver.scala)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at slick.backend.DatabaseConfig$.forConfig(DatabaseConfig.scala:84)
	at slick.backend.DatabaseConfig$.forConfig(DatabaseConfig.scala:57)
	at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.create(SlickApi.scala:89)
	at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.get$lzycompute(SlickApi.scala:81)
	at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.get(SlickApi.scala:80)
	at play.api.db.slick.DefaultSlickApi.dbConfig(SlickApi.scala:66)
	at play.api.db.slick.DatabaseConfigProvider$DatabaseConfigLocator$.apply(DatabaseConfigProvider.scala:81)
	at play.api.db.slick.DatabaseConfigProvider$.get(DatabaseConfigProvider.scala:103)
	at models.SqlServices.dbConfig$lzycompute(Services.scala:14)
	at models.SqlServices.dbConfig(Services.scala:14)
	at models.SqlServices.defaultDB(Services.scala:16)
	at models.database.structures.StandardService$class.db(SqlAbstractions.scala:91)
	at models.database.structures.StaticDataService.db$lzycompute(StaticData.scala:34)
	at models.database.structures.StaticDataService.db(StaticData.scala:34)
	at models.database.structures.StandardService$class.findWhere(SqlAbstractions.scala:112)
	at models.database.structures.StaticDataService.findWhere(StaticData.scala:34)
	at models.database.structures.StaticDataService.allTimezones(StaticData.scala:38)
	at controllers.StaticController$$anonfun$listTimezones$1.apply(StaticController.scala:59)
	at controllers.StaticController$$anonfun$listTimezones$1.apply(StaticController.scala:58)
	at play.api.mvc.Action$.invokeBlock(Action.scala:533)
	at play.api.mvc.Action$.invokeBlock(Action.scala:530)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741)
	at play.api.libs.iteratee.DoneIteratee$$anonfun$mapM$2.apply(Iteratee.scala:741)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
And here is MyPostgresqlDriver
```scala
trait MyPostgresDriver extends ExPostgresDriver
                      with PgArraySupport
                      with PgDateSupportJoda
                      with PgPlayJsonSupport {
	override val pgjson = "jsonb" //to keep back compatibility, pgjson's value was "json" by default

	override val api = MyAPI

	object MyAPI extends API with ArrayImplicits with SimpleArrayPlainImplicits
	                          with DateTimeImplicits
	                          with JsonImplicits
	                          with JodaDateTimePlainImplicits
	                          with PlayJsonPlainImplicits {

		implicit val strListTypeMapper = new SimpleArrayJdbcType[String]("text").to(_.toList)

		implicit val playJsonArrayTypeMapper =
			new AdvancedArrayJdbcType[JsValue](pgjson,
				(s) => utils.SimpleArrayUtils.fromString[JsValue](Json.parse(_))(s).orNull,
				(v) => utils.SimpleArrayUtils.mkString[JsValue](_.toString())(v)
			).to(_.toList)
	}

}
```

**Comment by tminglei** [comment]
Hi @sundriver, there're nothing to be worried about, since it's just a warning.
But I'll continue to find out why.

**Comment by sundriver** [comment]
Thanks @tminglei , appreciated.

**Comment by tminglei** [comment]
Hi @sundriver, I emulated your case on local, but can't reproduce it. Why?

**Comment by tminglei** [comment]
_Well, I turned the exception to warning message only at this [commit](https://github.com/tminglei/slick-pg/commit/c76f5fc4477aada484a6d13360688b7ad262fe15)._
