### ISSUE TITLE
don't work JsonImplicits

### ISSUE THREAD

**Issue by m-walk** [tminglei/slick-pg#206]
JsonImplicits does not work. it is an error to run insert or update.

I using 
slick-pg 0.9.2 
play 2.4.2 
play-slick 1.0.1 
Slick 3.0.1

I write JsonImplicits's source code to driver. 
it is work. 

success setting
```scala
package utils

import com.github.tminglei.slickpg._
import com.github.tminglei.slickpg.json.PgJsonExtensions
import org.json4s.JValue
import slick.jdbc.JdbcType

trait PGDriver extends ExPostgresDriver
                   with PgJson4sSupport
                   with PgArraySupport
                   with PgDateSupportJoda {

  override val pgjson = "jsonb"

  type DOCType = text.Document
  override val jsonMethods = org.json4s.native.JsonMethods

  override val api = PgAPI

  object PgAPI extends API
                 with Json4sJsonPlainImplicits
                 with ArrayImplicits
                 with JodaDateTimeFormatters
                 with SimpleArrayImplicits
                 with SimpleArrayPlainImplicits {
    implicit val json4sJsonTypeMapper =
      new GenericJdbcType[JValue](
        pgjson,
        (s) => jsonMethods.parse(s),
        (v) => jsonMethods.compact(jsonMethods.render(v)),
        hasLiteralForm = false
      )

    implicit def json4sJsonColumnExtensionMethods(c: Rep[JValue])(
      implicit tm: JdbcType[JValue], tm1: JdbcType[List[String]]) = {
      new JsonColumnExtensionMethods[JValue, JValue](c)
    }
    implicit def json4sJsonOptionColumnExtensionMethods(c: Rep[Option[JValue]])(
      implicit tm: JdbcType[JValue], tm1: JdbcType[List[String]]) = {
      new JsonColumnExtensionMethods[JValue, Option[JValue]](c)
    }
  }

}

object PGDriver extends PGDriver
```

error setting
```scala
package utils

import com.github.tminglei.slickpg._
import com.github.tminglei.slickpg.json.PgJsonExtensions
import org.json4s.JValue
import slick.jdbc.JdbcType

trait PGDriver extends ExPostgresDriver
                  with PgJson4sSupport
                  with PgArraySupport
                  with PgDateSupportJoda {

  override val pgjson = "jsonb"

  type DOCType = text.Document
  override val jsonMethods = org.json4s.native.JsonMethods

  override val api = PgAPI

  object PgAPI extends API
                  with JsonImplicits
                  with Json4sJsonPlainImplicits
                  with ArrayImplicits
                  with JodaDateTimeFormatters
                  with SimpleArrayImplicits
                  with SimpleArrayPlainImplicits { }
}

object PGDriver extends PGDriver
```

stacktrace is
```
[info] >>> adding next array converter for Short
[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] play.api.Play - Application started (Dev)
Exception in thread "db-7" java.lang.NoSuchMethodError: org.json4s.JsonMethods.render(Lorg/json4s/JsonAST$JValue;)Ljava/lang/Object;
	at com.github.tminglei.slickpg.PgJson4sSupport$Json4sJsonImplicits$$anonfun$2.apply(PgJson4sSupport.scala:23)
	at com.github.tminglei.slickpg.PgJson4sSupport$Json4sJsonImplicits$$anonfun$2.apply(PgJson4sSupport.scala:23)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.mkPgObject(PgCommonJdbcTypes.scala:33)
	at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.setValue(PgCommonJdbcTypes.scala:26)
	at slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:19)
	at slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:11)
	at slick.relational.CompoundResultConverter.set(ResultConverter.scala:98)
	at slick.relational.ProductResultConverter.set(ResultConverter.scala:71)
	at slick.relational.ProductResultConverter.set(ResultConverter.scala:46)
	at slick.relational.TypeMappingResultConverter.set(ResultConverter.scala:127)
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$slick$driver$JdbcInsertInvokerComponent$BaseInsertInvoker$$f$1$1.apply(JdbcInsertInvokerComponent.scala:217)
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$slick$driver$JdbcInsertInvokerComponent$BaseInsertInvoker$$f$1$1.apply(JdbcInsertInvokerComponent.scala:215)
	at slick.jdbc.JdbcBackend$SessionDef$class.withPreparedStatement(JdbcBackend.scala:304)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:388)
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.preparedInsert(JdbcInsertInvokerComponent.scala:177)
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.slick$driver$JdbcInsertInvokerComponent$BaseInsertInvoker$$f$1(JdbcInsertInvokerComponent.scala:215)
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$insertOrUpdate$2.apply(JdbcInsertInvokerComponent.scala:223)
	at slick.jdbc.JdbcBackend$BaseSession.withTransaction(JdbcBackend.scala:424)
	at slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.insertOrUpdate(JdbcInsertInvokerComponent.scala:223)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$$anonfun$insertOrUpdate$1.apply(JdbcActionComponent.scala:461)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$$anonfun$insertOrUpdate$1.apply(JdbcActionComponent.scala:461)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$$anon$8.run(JdbcActionComponent.scala:449)
	at slick.driver.JdbcActionComponent$InsertActionComposerImpl$$anon$8.run(JdbcActionComponent.scala:447)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:231)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tminglei** [comment]
Don't know why.
Can I see your usage code?

**Comment by m-walk** [comment]
I use codes and sbt.
Is there anything else you need?

```
name := """test"""

version := "1.0.0"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.7"

libraryDependencies ++= Seq(
  cache,
  filters,
  ws,
  "com.github.tminglei" % "slick-pg_2.11" % "0.9.2",
  "com.github.tototoshi" %% "play-json4s-native" % "0.4.1",
  "com.typesafe.play" %% "play-slick" % "1.0.1",
  "com.typesafe.slick" %% "slick" % "3.0.1",
  "org.postgresql" % "postgresql" % "9.4-1201-jdbc41",
)

routesGenerator := InjectedRoutesGenerator
```
```
package controllers

import com.google.inject.{Inject, Singleton}
import models.dao.{TestLog, TestLogDAO}
import org.json4s.native.JsonMethods
import play.api.mvc.{Action, Controller}
import scala.concurrent.ExecutionContext

@Singleton
class TestLogController @Inject()(testLog: TestLogDAO)(implicit ctx: ExecutionContext) extends Controller {

  def insert() = Action { implicit request =>
    val json = JsonMethods.parse(""" { "numbers" : [1, 2, 3, 4] } """)
    testLog.insert(TestLog(json))
    Ok("complete")
  }

}
```

```
package models.dao

import com.google.inject.{Inject, Singleton}
import org.json4s.JsonAST._
import play.api.db.slick._
import utils.PGDriver

import scala.concurrent.ExecutionContext

case class TestLog(json: JValue)

@Singleton
class TestLogDAO @Inject()(protected val dbConfigProvider: DatabaseConfigProvider)(implicit ec: ExecutionContext) extends HasDatabaseConfigProvider[PGDriver] {

  import driver.api._

  class TestTable(tag: Tag) extends Table[TestLog](tag, "test_log") {

    def json = column[JValue]("json")

    def * = json <>(TestLog.apply, TestLog.unapply)

  }

  private val testQuery = TableQuery[TestTable]

  def insert(testLog: TestLog) = db.run(
    testQuery += testLog
  ).map(_ => ())
}
```

**Comment by tminglei** [comment]
Well, `play-json4s-native` used `json4s-native v3.2.11`, which is a bad version, since it changed the `render` api.
If you can force to use `json4s-native v3.2.10` or other versions, the problem should be resolved.

**Comment by m-walk** [comment]
json4s-native v3.2.10 is work.
thanks!!

**Comment by tminglei** [comment]
_Sounds good! ;)_
