### ISSUE TITLE
java.lang.NoSuchMethodError: scala.runtime.BooleanRef.create(Z) when using List[T]

### ISSUE THREAD

**Issue by jacoffee** [tminglei/slick-pg#207]
The following code would work normally if I remove the column hobbies(type is List[Int]), but with this column, it will throw exception.
Version info: **```Scala 2.10.5```**,  **```PostgreSQL 9.4```**, **```Slick 3.0```**.

 ```scala
import slick.lifted.{ ProvenShape, Tag }
import scala.concurrent.Await
import scala.concurrent.duration.Duration
// MyPostgresDriver -- exactly the same with the code in https://github.com/tminglei/slick-pg
import allen.scalabasic.slick.MyPostgresDriver.api._

case class Student(name: String, age: Int, hobbies: List[Int])
class Students(tag: Tag) extends Table[Student](tag, "students") {
	def name = column[String]("name")
	def age = column[Int]("age")
	def hobbies = column[List[Int]]("hobbies")

	override def * : ProvenShape[Student] = (name, age, hobbies) <> 
              (Student.tupled, Student.unapply _)
}

object SlickPGTest extends App {

       // resume is one of my db
	val db = Database.forURL("jdbc:postgresql://localhost/resume", driver = "org.postgresql.Driver")
	val studentQuery = TableQuery[Students]
	val student = Student("allen", 25, List(1, 2))

	Await.result(
		db.run({
			DBIO.seq(
				studentQuery.schema.create,
				studentQuery += student
			)
		}),
		Duration.Inf
	)
}
```

Part of the exception stack trace:

 ```scala   
Exception in thread "AsyncExecutor.default-1" java.lang.NoSuchMethodError: scala.runtime.BooleanRef.create(Z)Lscala/runtime/BooleanRef;
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.com$github$tminglei$slickpg$utils$PgTokenHelper$$mergeString$2(PgTokenHelper.scala:128)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.createString(PgTokenHelper.scala:143)
	at com.github.tminglei.slickpg.utils.SimpleArrayUtils$.mkString(SimpleArrayUtils.scala:20)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.buildArrayStr(PgArrayJdbcTypes.scala:46)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType$$anonfun$mkArray$1.apply(PgArrayJdbcTypes.scala:44)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType$$anonfun$mkArray$1.apply(PgArrayJdbcTypes.scala:44)
	at com.github.tminglei.slickpg.utils.SimpleArrayUtils$SimpleArray.toString(SimpleArrayUtils.scala:60)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.setArray(AbstractJdbc2Statement.java:3031)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.setValue(PgArrayJdbcTypes.scala:35)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.setValue(PgArrayJdbcTypes.scala:22)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.setValue(PgArrayJdbcTypes.scala:120)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.setValue(PgArrayJdbcTypes.scala:111)
	at slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:19)
	at slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:11)
	at slick.relational.ProductResultConverter.set(ResultConverter.scala:71)
	at slick.relational.ProductResultConverter.set(ResultConverter.scala:46)
        ....
```

Try to find out why but have no idea where to start, any help would be appreciated!

**Comment by tminglei** [comment]
Don't know why.
Can you provide more details? I'll try to reproduce it on my local.

**Comment by jacoffee** [comment]
@tminglei Actually, if it is at your convenience, you can just copy the code and run on your local, I guess the error will reproduce. Besides, what do you mean by more details?

**Comment by tminglei** [comment]
@jacoffee, `slick-pg`'s tests covered your case, they all passed, so I don't think copying and pasting can reproduce the problem.

_To an ideal degree from my view, if you can create a simple project, which only includes codes that reproduce the problem, that will be great to help us find out the cause quickly. ;-)_

If that's not convenient, you'd better to provide the codes of your `MyPostgresDriver`. There're many `MyPostgresDriver` in tests of `slick-pg`, I don't know which one you're referencing.

And, it's better to tell the slick-pg version you're using.
