### ISSUE TITLE
Can't use Array's in GetResult

### ISSUE THREAD

**Issue by schmitch** [tminglei/slick-pg#217]
Hello, I tried to use the Array type in Get Results like that:
```
  implicit def GetResultArticleListData: GR[ArticleListData] = GR { prs => import prs._
    ArticleListData(<<[Long], <<[String], <<?[java.sql.Timestamp].map(_.toLocalDateTime), <<[Long],
      <<[String], <<[String], <<[String], <<[String], <<[String], <<[String],
      <<[String], <<[String], <<[String], <<[String], <<?[Seq[String]].map(_.toList))
  }```

My driver is here:

```
object PostgresDriver extends PostgresDriver

trait PostgresDriver extends driver.PostgresDriver
with PgArraySupport
with PgRangeSupport
with PgHStoreSupport
with PgPlayJsonSupport
with PgNetSupport
with PgLTreeSupport
with PgDate2Support {
  override val pgjson = "jsonb" //to keep back compatibility, pgjson's value was "json" by default

  override val api = MyAPI

  object MyAPI extends API
  with ArrayImplicits
  with SimpleArrayPlainImplicits
  with PlayJsonImplicits
  with PlayJsonPlainImplicits
  with NetImplicits
  with LTreeImplicits
  with RangeImplicits
  with HStoreImplicits
  with Date2DateTimeImplicitsDuration
  with Date2DateTimePlainImplicits
  with MoneyImplicits
  with WithBlob
  with WithUUID
  
}
```

However this is what I get:

```
could not find implicit value for parameter f: slick.jdbc.GetResult[Option[Seq[String]]]
In /Users/schmitch/projects/envisia/erp/loki/app/envisia/article/daos/ArticleListDao.scala:24

  implicit def GetResultArticleListData: GR[ArticleListData] = GR { prs => import prs._

    ArticleListData(<<[Long], <<[String], <<?[java.sql.Timestamp].map(_.toLocalDateTime), <<[Long],

      <<[String], <<[String], <<[String], <<[String], <<[String], <<[String],
      <<[String], <<[String], <<[String], <<[String], <<?[Seq[String]].map(_.toList)) 
  }```

tried slick-pg 0.9.1 and now 0.10.0 both are failing.. do I miss something?!

**Comment by schmitch** [comment]
Additional Details, If I set it manually:

```
  implicit def GetResultArticleListData: GR[ArticleListData] = GR { prs => import prs._
    ArticleListData(<<[Long], <<[String], <<?[java.sql.Timestamp].map(_.toLocalDateTime), <<[Long],
      <<[String], <<[String], <<[String], <<[String], <<[String], <<[String],
      <<[String], <<[String], <<[String], <<[String], prs.nextArrayOption[String].map(_.toList))
  }
```

I will get a 
```
java.lang.AbstractMethodError: utils.PostgresDriver$.slick$driver$JdbcProfile$_setter_$simple_$eq(Lslick/driver/JdbcProfile$SimpleQL;)V

     slick.driver.JdbcProfile$class.$init$(JdbcProfile.scala:92)

     utils.PostgresDriver$.<init>(PostgresDriver.scala:12)

     utils.PostgresDriver$.<clinit>(PostgresDriver.scala)

     sun.misc.Unsafe.ensureClassInitialized(Native Method)

     sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)

     sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)

     java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)

     java.lang.reflect.Field.getFieldAccessor(Field.java:1069)

     java.lang.reflect.Field.get(Field.java:393)

     slick.backend.DatabaseConfig$.forConfig(DatabaseConfig.scala:84)

     slick.backend.DatabaseConfig$.forConfig(DatabaseConfig.scala:57)

     play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.create(SlickApi.scala:89)

     play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.get$lzycompute(SlickApi.scala:81)

     play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.get(SlickApi.scala:80)

     play.api.db.slick.DefaultSlickApi$$anonfun$allDbConfigs$1.apply(SlickApi.scala:59)

     play.api.db.slick.DefaultSlickApi$$anonfun$allDbConfigs$1.apply(SlickApi.scala:59)

     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)

     scala.collection.immutable.Map$Map2.foreach(Map.scala:137)

     scala.collection.TraversableLike$class.map(TraversableLike.scala:245)

     scala.collection.AbstractTraversable.map(Traversable.scala:104)

     play.api.db.slick.DefaultSlickApi.allDbConfigs$lzycompute(SlickApi.scala:59)

     play.api.db.slick.DefaultSlickApi.allDbConfigs(SlickApi.scala:58)

     play.api.db.slick.DefaultSlickApi.dbConfigs(SlickApi.scala:62)

     play.api.db.slick.evolutions.internal.DBApiAdapter.databasesByName$lzycompute(DBApiAdapter.scala:19)

     play.api.db.slick.evolutions.internal.DBApiAdapter.databasesByName(DBApiAdapter.scala:19)

     play.api.db.slick.evolutions.internal.DBApiAdapter.databases(DBApiAdapter.scala:23)

     play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)

     play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:149)

     play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)

     play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)

     play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)

     com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)

     com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)

     com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)

     com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)

     com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)

     com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)

     com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)

     com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)

     com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)

     com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)

     com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)

     com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)

     com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)

     com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)

     com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)

     com.google.inject.Guice.createInjector(Guice.java:96)

     com.google.inject.Guice.createInjector(Guice.java:73)

     com.google.inject.Guice.createInjector(Guice.java:62)

     play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)

     play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)

     play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150)

     play.utils.Threads$.withContextClassLoader(Threads.scala:21)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121)

     scala.Option.map(Option.scala:146)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119)

     scala.util.Success.flatMap(Try.scala:230)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119)

     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)

     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)

     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)

     java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)

     java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)

     java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)

     java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)

     java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by schmitch** [comment]
Oh looks like using the following works:
```
  implicit def GetResultArticleListData: GR[ArticleListData] = GR { prs => import prs._
    ArticleListData(<<[Long], <<[String], <<?[java.sql.Timestamp].map(_.toLocalDateTime), <<[Long],
      <<[String], <<[String], <<[String], <<[String], <<[String], <<[String],
      <<[String], <<[String], <<[String], <<[String], prs.nextArrayOption[String].map(_.toList))
  }
```

Driver:
```
object PostgresDriver extends PostgresDriver

trait PostgresDriver extends driver.PostgresDriver
with PgArraySupport
//with PgRangeSupport
//with PgHStoreSupport
//with PgLTreeSupport
with PgPlayJsonSupport
with PgNetSupport
with PgDate2Support {
  override val pgjson = "jsonb" //to keep back compatibility, pgjson's value was "json" by default

  override val api = MyAPI

  object MyAPI extends API
  with ArrayImplicits
  with SimpleArrayPlainImplicits
  with PlayJsonImplicits
  with PlayJsonPlainImplicits
  with NetImplicits
//  with LTreeImplicits
//  with RangeImplicits
//  with HStoreImplicits
  with Date2DateTimeImplicitsDuration
  with Date2DateTimePlainImplicits
  with MoneyImplicits
  with WithBlob
  with WithUUID

}
```

However on play reload my application has a stack trace:
```
java.lang.RuntimeException: [warn] >>> DUPLICATED converter for Short!!!  If it's expected, pls ignore it.
	at com.github.tminglei.slickpg.utils.PlainSQLUtils$.addNextArrayConverter(PlainSQLUtils.scala:16)
	at com.github.tminglei.slickpg.PgArraySupport$SimpleArrayPlainImplicits$class.$init$(PgArraySupport.scala:45)
	at utils.PostgresDriver$MyAPI$.<init>(PostgresDriver.scala:22)
	at utils.PostgresDriver$.MyAPI$lzycompute(PostgresDriver.scala:8)
	at utils.PostgresDriver$.MyAPI(PostgresDriver.scala:8)
	at utils.PostgresDriver$class.$init$(PostgresDriver.scala:20)
	at utils.PostgresDriver$.<init>(PostgresDriver.scala:8)
	at utils.PostgresDriver$.<clinit>(PostgresDriver.scala)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at slick.backend.DatabaseConfig$.forConfig(DatabaseConfig.scala:62)
	at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.create(SlickApi.scala:89)
	at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.get$lzycompute(SlickApi.scala:81)
	at play.api.db.slick.DefaultSlickApi$DatabaseConfigFactory.get(SlickApi.scala:80)
	at play.api.db.slick.DefaultSlickApi$$anonfun$allDbConfigs$1.apply(SlickApi.scala:59)
	at play.api.db.slick.DefaultSlickApi$$anonfun$allDbConfigs$1.apply(SlickApi.scala:59)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at play.api.db.slick.DefaultSlickApi.allDbConfigs$lzycompute(SlickApi.scala:59)
	at play.api.db.slick.DefaultSlickApi.allDbConfigs(SlickApi.scala:58)
	at play.api.db.slick.DefaultSlickApi.dbConfigs(SlickApi.scala:62)
	at play.api.db.slick.evolutions.internal.DBApiAdapter.databasesByName$lzycompute(DBApiAdapter.scala:19)
	at play.api.db.slick.evolutions.internal.DBApiAdapter.databasesByName(DBApiAdapter.scala:19)
	at play.api.db.slick.evolutions.internal.DBApiAdapter.databases(DBApiAdapter.scala:23)
	at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
	at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:149)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)
	at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121)
	at scala.Option.map(Option.scala:146)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119)
	at scala.util.Success.flatMap(Try.scala:231)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by tminglei** [comment]
Well, you can ignore the exception, since it's a warning.
_BTW, I just turn the exception to warning message only [here](https://github.com/tminglei/slick-pg/commit/c76f5fc4477aada484a6d13360688b7ad262fe15)._

**Comment by tminglei** [comment]
And, your original codes should work for slick-pg v0.9.2, v0.10.0

**Comment by schmitch** [comment]
Currently It only works if I use 'nextArrayOption' the ``<<?``` does not work.

**Comment by tminglei** [comment]
Well, I don't know why for that.

**Comment by milanvdmria** [comment]
@tminglei Im having exactly the same issue though.

```
implicit val getMedicineResult = GetResult(r =>
      Medicine(r.<<?[String], r.<<?[String], r.<<?[String], r.<<?[Seq[String]].map(_.toList), r.<<?[String]))
``` 

throws on build time the following:

```
Error:(19, 66) could not find implicit value for parameter f: slick.jdbc.GetResult[Option[Seq[String]]]
      Medicine(r.<<?[String], r.<<?[String], r.<<?[String], r.<<?[Seq[String]].map(_.toList), r.<<?[String]))
```

and im using the following profile:
```
package database

import com.github.tminglei.slickpg._
import com.github.tminglei.slickpg.trgm.PgTrgmSupport

trait MyPostgresProfile extends ExPostgresProfile
    with PgArraySupport
    with PgDateSupport
    with PgDate2Support
    with PgJsonSupport
    with PgNetSupport
    with PgLTreeSupport
    with PgRangeSupport
    with PgHStoreSupport
    with PgSearchSupport
    with PgTrgmSupport {

  override val pgjson = "jsonb"
  ///
  override val api: API = new API {}

  trait API extends super.API
    with ArrayImplicits
    with SimpleDateTimeImplicits
    with DateTimeImplicits
    with SimpleJsonImplicits
    with NetImplicits
    with LTreeImplicits
    with RangeImplicits
    with HStoreImplicits
    with SearchImplicits
    with SearchAssistants
    with PgTrgmImplicits

}

object MyPostgresProfile extends MyPostgresProfile
```
