### ISSUE TITLE
Invalid format is too short

### ISSUE THREAD

**Issue by simao** [tminglei/slick-pg#220]
Hi,

When using joda time with slick-pg I get the following error when reading a record from the database:

    Invalid format: "2015-10-16 15:56:04.041" is too short.

Is this a known problem? Seems the database is returning a string without the timezone.

In the database the record is stored as "2015-10-16 15:56:04.041+02"

Thank you

**Comment by prettynatty** [comment]
I have the same problem with LocalDateTime column (timestamp in Postgres)

**Comment by rockjam** [comment]
Same problem with LocalDateTime

**Comment by motns** [comment]
Out of curiosity, what version of **Slick**, **slick-pg** and **Postgres JDBC** are you guys using? I'm only asking because I had pretty much the same problem a while back when I upgraded my version of the JDBC driver from `9.4-1201-jdbc41` to `9.4-1203-jdbc42`, while using **Slick** `3.0.1` and **slick-pg** `0.9.2`. I didn't have time to fully investigate (I just rolled back to the older JDBC driver which fixed it), but from the limited time I spent debugging it, it seemed like that the actual JDBC driver itself was returning `TIMESTAMP WITH TIMEZONE` columns without the actual Time Zone at the end...

I haven't looked at this since, but I tried to reproduce it just now with **Slick** `3.1.0` and **slick-pg** `0.10.0`, upgrading the Postgres driver to the latest version (`9.4-1204-jdbc42`), and I don't seem to get the error any more, so maybe whatever was causing it has been fixed.

**Comment by motns** [comment]
Scratch that - it does seem to be broken still. Everything works fine with Postgres driver version `9.4-1201-jdbc41`, but using version `9.4-1202-*` and above results in an error. Here's an example stack trace:
```
DateTimeParseException: Text '2015-07-24 16:14:13.0' could not be parsed at index 21
    at java.lang.Thread.run
    at java.util.concurrent.ThreadPoolExecutor$Worker.run
    at java.util.concurrent.ThreadPoolExecutor.runWorker
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1
    at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run
    at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run
    at slick.jdbc.StreamingInvokerAction$class.run
    at slick.jdbc.StatementInvoker.foreach
    at slick.jdbc.Invoker$class.foreach
    at slick.jdbc.PositionedResultIterator.foreach
    at scala.collection.Iterator$class.foreach
    at slick.jdbc.PositionedResultIterator.hasNext
    at slick.util.ReadAheadIterator$class.hasNext
    at slick.util.ReadAheadIterator$class.slick$util$ReadAheadIterator$$update
    at slick.jdbc.PositionedResultIterator.fetchNext
    at slick.jdbc.StatementInvoker$$anon$1.extractValue
    at slick.driver.JdbcInvokerComponent$QueryInvokerImpl.extractValue
    at slick.relational.TypeMappingResultConverter.read
    at slick.relational.ProductResultConverter.read
    at slick.relational.ProductResultConverter.read
    at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read
    at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read
    at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.getValue
    at com.github.tminglei.slickpg.PgDate2Support$Date2DateTimeFormatters$$anonfun$fromInfinitable$1.apply
    at com.github.tminglei.slickpg.PgDate2Support$Date2DateTimeFormatters$$anonfun$fromInfinitable$1.apply
    at com.github.tminglei.slickpg.PgDate2Support$Date2DateTimeFormatters$$anonfun$4.apply
    at com.github.tminglei.slickpg.PgDate2Support$Date2DateTimeFormatters$$anonfun$4.apply
    at java.time.ZonedDateTime.parse
    at java.time.format.DateTimeFormatter.parse
    at java.time.format.DateTimeFormatter.parseResolved0
```
I had a quick look at the issues for the Postgres driver on GitHub (https://github.com/pgjdbc/pgjdbc) and didn't immediately see anything related, so maybe this is somehow expected behavior? I don't have much experience with using JDBC directly, so I can't tell...

@tminglei - what do you think?

**Comment by tminglei** [comment]
Hey guys, I just upgraded posgres driver to `9.4-1204`. Changes' [here](https://github.com/tminglei/slick-pg/commit/9e6c0d1e4a52d6b2a92592d5c14acd7755f089f1).
Yes, I encountered some problems, but it's not related to this issue.

_I haven't reproduced the problem, maybe you guys can paste some usable codes?_

**Comment by simao** [comment]
Hi, 

I will try to write a failing test during the weekend, see if I can isolate it. 

Thanks

**Comment by simao** [comment]
Hi.

I could not isolate this in a standalone project but I managed to write a test on my project where this happens.

I have the following code:

    val f = for {
      _ <- db.run(schema.vehicles += testVehicle)
      _ ← db.run(schema.vehicles.take(100).result)
      _ ← db.run(schema.vehicles.take(100).result)
      _ ← db.run(schema.vehicles.take(100).result)
      _ ← db.run(schema.vehicles.take(100).result)
      _ ← db.run(schema.vehicles.take(100).result)
      _ ← db.run(schema.vehicles.take(100).result)
    } yield ()

    whenReady(f) { _ =>

    }

If I remove a single one of those db.run(...result) then the test will be green. 

I don't do any special setup, just create some tables and this test runs alone, no other tests are running before/after/during.

This is really weird.

Thank you

**Comment by prettynatty** [comment]
@motns I have this error with both 9.4-1201-jdbc41 and 9.4-1202-*and above

**Comment by tminglei** [comment]
Can you guys provide reproduce codes? I can't reproduce it yet.

**Comment by joakim-ribier** [comment]
Hi,

I have the same error since the 0.10.1 release. The code is very simple, I try to fetch an user with a 'createdAt' field (TIMESTAMPTZ) in a Postgresql database. The first fetch is good, the "user.createdAt" equals to "2015-10-20 14:43:45.602+02" but the next, contains only the datetime without timezone "2015-10-20 14:43:45.602".

I have this code:
```
Schemas.users.filter(_.id === userInfo.userId).result.headOption
```

And the error:

```java.lang.IllegalArgumentException: Invalid format: "2015-10-20 14:43:45.602" is too short
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899) ~[joda-time-2.8.2.jar:2.8.2]
	at org.joda.time.DateTime.parse(DateTime.java:160) ~[joda-time-2.8.2.jar:2.8.2]
	at com.github.tminglei.slickpg.PgDateSupportJoda$JodaDateTimeImplicits$$anonfun$8.apply(PgDateSupportJoda.scala:40) ~[slick-pg_joda-time_2.11-0.10.1.jar:0.10.1]
	at com.github.tminglei.slickpg.PgDateSupportJoda$JodaDateTimeImplicits$$anonfun$8.apply(PgDateSupportJoda.scala:40) ~[slick-pg_joda-time_2.11-0.10.1.jar:0.10.1]
	at```

Thanks a lot

**Comment by damirv** [comment]
For me, this occurs at random it seems (Postgres 9.4.5, 9.4-1204-jdbc41, slick-pg 0.10.1). I don't know if this is related to slick-pg, as it gets fed a date time that is too short (it's missing the date time offset part). The weird thing is that when I just start my Play app, it works a couple of times, after that it stops working and I get each time the error described above. I'll see if I can get an app out there that demonstrates this problem.

**Comment by damirv** [comment]
I tried the following:

```
override def all: Future[Seq[User]] = {
  db.run(sql"select USERS.birth_date from USERS".as[(String)]).flatMap { birthdates =>
    println(birthdates)
    db.run(allUsers)
  }
}
```

When I get the error, the `println` statement outputs something like `Vector(2015-10-29 22:56:02.719)`, does this mean that the problem is actually in slick itself?

**Comment by maxcom** [comment]
I see the same problem. slick-pg 0.10.0, postgresql driver 9.4-1203-jdbc42.

**Comment by tminglei** [comment]
In codes of `slick-pg` date2 support, it first get string from result set, then parse the string value to `LocalDate/ZonedDateTime`.

I checked postgres driver's source codes, and here's the codes of `getString(columnIndex)`:
```java
    public String getString(int columnIndex) throws SQLException
    {
        checkResultSet( columnIndex );
        if (wasNullFlag)
            return null;

        // varchar in binary is same as text, other binary fields are converted to their text format
        if (isBinary(columnIndex) && getSQLType(columnIndex) != Types.VARCHAR) {
            Object obj = internalGetObject(columnIndex, fields[columnIndex - 1]);
            if (obj == null) {
                return null;
            }
            // hack to be compatible with text protocol
            if (obj instanceof java.util.Date) {
              return connection.getTimestampUtils().timeToString((java.util.Date) obj);
            }
            if ("hstore".equals(getPGType(columnIndex))) {
                return HStoreConverter.toString((Map) obj);
            }
            return trimString(columnIndex, obj.toString());
        }

        Encoding encoding = connection.getEncoding();
        try
        {
            return trimString(columnIndex, encoding.decode(this_row[columnIndex - 1]));
        }
        catch (IOException ioe)
        {
            throw new PSQLException(GT.tr("Invalid character data was found.  This is most likely caused by stored data containing characters that are invalid for the character set the database was created in.  The most common example of this is storing 8bit data in a SQL_ASCII database."), PSQLState.DATA_ERROR, ioe);
        }
    }
```
Note: for `timestamptz`, the return value of `getSQLType(columnIndex)` is `Types.TIMESTAMP`, and .

So if the column's format is `binary`, it will get into the `if` branch, call `internalGetObject(columnIndex, fields[columnIndex - 1])` , and get a `Timestamp` object, then ... the zone info was discarded.

**Comment by tminglei** [comment]
But the column format is always `text` in my test cases. So I can't reproduce it.

**Comment by damirv** [comment]
So you are able to reproduce it now? In my case the field is `TIMESTAMP WITH TIME ZONE`. I debugged in the `PgCommonJdbcTypes$GenericJdbcType#getValue` method, there the parsed string does not contain the offset. But it is still unclear to me why on server startup the field there does get parsed properly (i.e., with an offset).

**Comment by maxcom** [comment]
I have a REST endpoint that produces exactly the same SQL request on each call. Problem happens only when I repeat this call several times (apache benchmark is a good tool for it). 

Single requests in non-busy development environment always works fine.

**Comment by tminglei** [comment]
@damirv, I haven't reproduced it yet. I just found some cause.

**Comment by prettynatty** [comment]
I've got a bit more information: 

In my project(slick 3.0.3, slick-pg 0.9.0, postgresql 9.4-1201-jdbc41) I used https://github.com/tototoshi/slick-joda-mapper for joda DateTime. After switching to slick-pg's implicits tests started to throw this error.

**Comment by tminglei** [comment]
@prettynatty, I can't still reproduce it, with your tips.

**Comment by prettynatty** [comment]
I still can't localize it to a small project.

**Comment by faustas** [comment]
Hello,

I can confirm, that this bug also occurs with **ZonedDateTime** and correct data sets in the Postgresql database.

We use: `postgresql 9.4-1205-jdbc42, slick-pg 0.10.1, slick-pg_date 0.10.1, slick-pg_argonaut 0.10.1 and play-slick 1.1.1`.

In the Postgresql table the following *timestamp with time zone* is stored: `2015-11-10 15:51:08.497+01`

We get the following error:
```shell
2015-11-18 14:01:10,815 [error] a.a.OneForOneStrategy - Text '2015-11-10 15:51:08.497' could not be parsed at index 23
java.time.format.DateTimeParseException: Text '2015-11-10 15:51:08.497' could not be parsed at index 23
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947) ~[na:1.8.0_45-internal]
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1849) ~[na:1.8.0_45-internal]
	at java.time.ZonedDateTime.parse(ZonedDateTime.java:597) ~[na:1.8.0_45-internal]
	at com.github.tminglei.slickpg.PgDate2Support$Date2DateTimeFormatters$$anonfun$4.apply(PgDate2Support.scala:78) ~[slick-pg_date2_2.11-0.10.1.jar:0.10.1]
	at com.github.tminglei.slickpg.PgDate2Support$Date2DateTimeFormatters$$anonfun$4.apply(PgDate2Support.scala:78) ~[slick-pg_date2_2.11-0.10.1.jar:0.10.1]
```

The *time zone* is not delivered to `PgDate2Support` for parsing the value as *ZonedDateTime*

Would it be a solution to set the **system time zone**, if no *time zone* is available?

We tested also with the following postgresql versions: `9.4-1205-jdbc42 - 9.4-1200-jdbc42`

**Comment by tminglei** [comment]
@faustas, can you always reproduce it?

If yes, can you debug into `AbstractJdbc2ResultSet.getString(int columnIndex)`? I want to know whether `isBinary(columnIndex)` return `true` or `false`.

_BTW, I can't reproduce it on my local._

**Comment by faustas** [comment]
Hello,

I debugged the application and can tell you the following.

Within `AbstractJdbc2ResultSet.getString(int columnIndex)`, the `isBinary(columnIndex)` is **true**.

The following code `Object obj = internalGetObject(columnIndex, fields[columnIndex - 1]);` returns the Timestamp without the *Timezone*.

As far as I understand the problem:
* `getTimestamp` within `internalGetObject` already calculates the *Timezone* into the return value. Therefore, the time string does not need the *Timezone* anymore.

The final problem is the type conversion into **ZonedDateTime** which expects a **Timezone** at the parsed string.

**Comment by tminglei** [comment]
Hi @faustas, thanks! You confirmed my guess.
But I haven't a good solution to resolve it yet.

**Comment by jan0sch** [comment]
@tminglei Would it be possible to change the fetching logic for timestamp related values? I'm thinking in the direction of pulling them out as formatted datetime strings and parsing them afterwards. So far writing these values seems to work, therefore it should suffice to change the "read logic".

I currently have no idea how to implement that and I know that this is a "hack" but it would maybe provide a useable workaround as long as the postgresql guys haven't fixed that.

**Comment by tminglei** [comment]
@jan0sch, this is what I did in `slick-pg`. 

But the returned value `true` of `isBinary(columnIndex)` in `AbstractJdbc2ResultSet.getString(int columnIndex)` caused `pgjdbc` to run into a code branch, where it read a timestamp object, then covert it to string, and time zone info was lost in the process.

_See the codes from above comments of mine._

**Comment by jan0sch** [comment]
Ah, okay. So the problem is that the column is a binary one. Which means we would have to wait for a fix from the postgresql side or store timstamp values as strings and that would be rather ugly. :-(

**Comment by jan0sch** [comment]
This is just a quickshot but would something like this maybe provide a workaround until this is officially fixed?

````
diff --git a/org/postgresql/jdbc2/AbstractJdbc2ResultSet.java b/org/postgresql/jdbc2/AbstractJdbc2ResultS
index 64d949f..efbc370 100644
--- a/org/postgresql/jdbc2/AbstractJdbc2ResultSet.java
+++ b/org/postgresql/jdbc2/AbstractJdbc2ResultSet.java
@@ -2986,7 +2986,14 @@ public abstract class AbstractJdbc2ResultSet implements BaseResultSet, org.postg
      * @return True if the column is in binary format.
      */
     protected boolean isBinary(int column) {
-        return fields[column - 1].getFormat() == Field.BINARY_FORMAT;
+        Field f = fields[column - 1];
+        if (f.getPGType().equalsIgnoreCase("timestamptz") || f.getPGType().equalsIgnoreCase("timetz")) {
+            // Prevent binary treating of fields with timezone.
+            return false;
+        }
+        else {
+            return fields[column - 1].getFormat() == Field.BINARY_FORMAT;
+        }
     }
 
     //----------------- Formatting Methods -------------------
````

**Comment by jan0sch** [comment]
I've just realised that the problem roots far deeper. Forget that workaround. ;-)

**Comment by tminglei** [comment]
Well, we also need ensure the datetime binary can be decoded to string w/ time zone here:
```java
    // in AbstractJdbc2ResultSet.java
    public String getString(int columnIndex) throws SQLException
    {
        ...

        Encoding encoding = connection.getEncoding();
        try
        {
            return trimString(columnIndex, encoding.decode(this_row[columnIndex - 1]));
        }
        catch (IOException ioe)
        {
            throw new PSQLException(GT.tr("Invalid character data was found.  This is most likely caused by stored data containing characters that are invalid for the character set the database was created in.  The most common example of this is storing 8bit data in a SQL_ASCII database."), PSQLState.DATA_ERROR, ioe);
        }
    }
```

pls help continue totest it.

**Comment by jan0sch** [comment]
I'm short on time but I'll try to help as best as I can. *I just came to realise that the whole JDBC thing has no concept for timezones on times and timestamps. But I guess fixing JDBC would take a lot and brake a lot. ;-)*

**Comment by mdedetrich** [comment]
Im getting the same problem, and it has broken all of our code. Is there any workaround (i.e. can we downgrade the JDBC version)?

**Comment by maxcom** [comment]
@mdedetrich use java.sql.Timestamp

**Comment by mdedetrich** [comment]
@maxcom Not really an option, our entire codebase uses `DateTime`, and we have a huge amount of tables to deal with. Is there any other option?

**Comment by mdedetrich** [comment]
Forcefully setting the JDBC version to `"org.postgresql" % "postgresql" % "9.4-1201-jdbc41"` fixed the problem for me, so at least for our case, the upgrade of the JDBC version definitely broke something

**Comment by tminglei** [comment]
@mdedetrich, glad to hear that! _:-)_

_I also suspected new `pgjdbc` changes introduced the bug, but after checked the codes no suspicious codes found._

**Comment by jan0sch** [comment]
For us the bug did stay even if downgrading the postgresql driver version. We tried all versions from `94.-1201` to `9.4-1206` using their "jdbc4", "jdbc41" and "jdbc42" flavours.

Because we have time pressure we resolved to using `java.sql.Timestamp` database columns which are mapped via implicit conversions to the `java.time.ZonedDateTime` we use within the application.

**Comment by tminglei** [comment]
Another way to let it work (no crashing), _instead of `fixing` it_.

Override the timestamp w/ time zone type mapper in your customized postgres driver like this:
```scala
  object MyPostgresDriver extends PostgresDriver
                            ...
                            with PgDateSupportJoda {
    ...
    override val api = new API with DateTimeImplicits {
      def getDateTimeFormatter(s: String)  = {
        if(s.matches(".*[\\+|\\-][0-9]+$")) if(s.indexOf(".") > 0 ) jodaTzDateTimeFormatter else jodaTzDateTimeFormatter_NoFraction
        else if(s.indexOf(".") > 0 ) jodaDateTimeFormatter else jodaDateTimeFormatter_NoFraction
      }

      implicit override val jodaTimestampTZTypeMapper: GenericJdbcType[DateTime] = new GenericJdbcType[DateTime]("timestamptz",
        fnFromString = (s) => DateTime.parse(s, getDateTimeFormatter(s)),
        fnToString = (v) => v.toString(jodaTzDateTimeFormatter),
        hasLiteralForm = false)
    }
    ...
  }
```
Then it will auto survive when no time zone info found, and you needn't change your application codes.

_p.s. this is for `joda`, but you can easily update it for `java.time`._

**Comment by jan0sch** [comment]
Thanks for the hint.

As far as I've seen from the pgjdbc driver the time zone will definitely get lost when retrieving a timestamp from the database. This shouldn't be a problem if all timestamps are saved with the same time zone but in other cases the conversion into `java.sql.Timestamp` within the pgjdbc driver will lead to loss of information. :-(

In my opinion this should be fixed on the pgjdbc side because all we can do on the "outer layer" are workarounds.

Anyway, many thanks for writing this great extension to slick. :+1: :-)

**Comment by mdedetrich** [comment]
I am trying an implementation now, and its not completely trivial (as that other issue is describing), but I will see how it goes

**Comment by Daxten** [comment]
workaround for java8 and OffsetDateTime:

{

    val zoneOffset = ZoneOffset.from(OffsetDateTime.now)

    def string2Offset(s: String): OffsetDateTime =
      if (s.matches(".*[\\+|\\-][0-9]+$")) OffsetDateTime.parse(s, date2TzDateTimeFormatter)
      else OffsetDateTime.of(LocalDateTime.parse(s, date2DateTimeFormatter), zoneOffset)

    def offset2String(v: OffsetDateTime): String = v.format(date2TzDateTimeFormatter)

    implicit override val date2TzTimestampTypeMapper = new GenericJdbcType[OffsetDateTime]("timestamptz",
      fnFromString = string2Offset,
      hasLiteralForm = false,
      fnToString = offset2String
    )
  }

**Comment by mdedetrich** [comment]
@tminglei Would it be possible to downgrade the JDBC version back to a version that worked? I think for some people (I know definitely for me), thats what caused the issue.

Then maybe we should wait for the people at postgres-jdbc to fix the problem on their end

**Comment by tminglei** [comment]
@mdedetrich, I won't mind to do it, if it can really resolve the problem.
But as @jan0sch pointed in comment above, it can't.

So I'm not sure whether we should do it.

**Comment by damirv** [comment]
For me it did solve the problem (9.4-1201-jdbc41 and using OffsetDateTime)

Met vriendelijke groet,

Damir Vandic | Ontostream

**Comment by tminglei** [comment]
Well, I think I found the cause.

There's a method in `AbstractJdbc2Statement.java` like this:
```java
    public void setPrepareThreshold(int newThreshold) throws SQLException {
        checkClosed();
       
        if (newThreshold < 0) {
            forceBinaryTransfers = true;
            newThreshold = 1;
        }

        this.m_prepareThreshold = newThreshold;
    }
```

And from postgres driver `9.4-1202-*`, it was called in `AbstractJdbc2Statement` constructor.
And at the same time, `CachedQuery` was used in `AbstractJdbc2Statement` constructor.

_The `forceBinaryTransfers` will force postgres db backend to send binary back. Then based on the logic `getString(columnIndex)` of `AbstractJdbc2ResultSet.java` I pasted in comment above, it lead to the timestamptz data was converted to `java.sql.Timestamp` then to string, and the time zone part was lost from the final string._

**So, downgrade to `9.4-1201-*` can resolve the problem.**

I will do it ASAP.

**Comment by tminglei** [comment]
Hi all, I downgrade postgres driver to 9.4-1201-jdbc41 to resolve the problem temporarily.
Pls update your project dependencies to use it.

**Comment by Daxten** [comment]
Thanks for the update!

**Comment by veegee** [comment]
Have this same problem. Downgrading the driver fixes it.

**Comment by pschorf** [comment]
FWIW, I didn't see this issue and had the same problem. I worked around it by replacing the column type to one mapped to time stamp instead of mapped to String. I will test with the lower Postrgresql version today.

**Comment by mdedetrich** [comment]
Not sure why, but I am still getting this in the latest version of slick-pg v0.14.2, and I have cycled through the following postgres jdbc versions

```scala
  "org.postgresql"       %  "postgresql"            % "9.4-1201-jdbc41" force(),
  "org.postgresql"       %  "postgresql"            % "9.4-1208-jdbc41" force(),
  "org.postgresql"       % "postgresql"             % "9.4.1208.jre7" force()
```

And I am getting an error in all of the cases

**Comment by Daxten** [comment]
dont import any driver, there should be one bundled in the pg-slick dependency

**Comment by mdedetrich** [comment]
@Daxten Its not working on my end, also the one that is bundled with pg-slick is also one of the ones that I tried before

```scala
"org.postgresql" % "postgresql" % "9.4-1201-jdbc41" force()
```

You can check here https://github.com/tminglei/slick-pg/blob/v0.14.2/project/Build.scala#L71

I am suspecting that its an issue with using `OffsetDateTime` as a column, rather than the driver being used

**Comment by TimothyKlim** [comment]
It seems like this problem has been fixed in jdbc driver 9.4.2109 version (tested on psql 9.5.3, slick 3.2.0-M1 and slick-pg-0.15.0-M1).

**Comment by mdedetrich** [comment]
@TimothyKlim What version of postgresql jdbc is 9.4.2109, such a version doesn't seem to exist?

https://mvnrepository.com/artifact/org.postgresql/postgresql

**Comment by Daxten** [comment]
bet he ment 1209

**Comment by TimothyKlim** [comment]
Oh, right, I mean 1209 version.

**Comment by tminglei** [comment]
Just upgrade postgres driver to v9.4.1209 in brach [next](https://github.com/tminglei/slick-pg/tree/next).
Can you guys help to check it?

_Thanks!_

**Comment by mdedetrich** [comment]
@tminglei I can't use the driver from the next branch because it breaks all of the code, however I have tried `0.14.2` with v9.4.1209 and it hasn't worked

**Comment by mdedetrich** [comment]
Actually figured out the issue, the databse has column type `TIMESTAMP WITHOUT TIME ZONE` rather than `TIMESTAMP WITH TIME ZONE`, its working now

**Comment by damirv** [comment]
Maybe someone can share a public Github test repo so we can try it out? (I don't have a test project set up anymore for this issue)

**Comment by danishin** [comment]
I tested with 
```
"org.postgresql" % "postgresql" % "9.4.1209",
"com.typesafe.slick" %% "slick" % "3.1.1",
"com.github.tminglei" %% "slick-pg" % "0.14.2",
// ...
```

And it works! Thank you @tminglei

**Comment by tminglei** [comment]
@danishin yes, postgres JDBC `9.4.1209` already resolved the issue.
So if your postgres driver is later than `9.4.1209`, you won't be bothered by the issue.

**Comment by tminglei** [comment]
@danishin glad to hear that! _You're welcome! :-)_

**Comment by binshi** [comment]
As a work around till the issue is resolved,  one can also add https://github.com/tototoshi/slick-joda-mapper

**Comment by ShurikAg** [comment]
For me, upgrading to `9.4.1212` fixed the problem.
