### ISSUE TITLE
Should it be possible to create index using json operators ?

### ISSUE THREAD

**Issue by cppexpert** [tminglei/slick-pg#254]
I'm new to Slick so I'm not sure if it's possible at all but it compiles. Should it be possible to create index using json operators ?

Here is what I have

```scala
  protected class ArticleRow(tag: Tag) extends Table[Article](tag, "articles") {

    def id = column[ObjectId]("id", O.PrimaryKey)
    def idsJson = column[JsValue]("ext_ids") // Optional external IDs

    def idx_doi = index("idx_doi", idsJson +>> "doi", unique = true)
}
```

I'm trying to make it create following index

```
CREATE UNIQUE INDEX idx_doi ON articles ((ext_ids ->> 'doi'));
```

but I get this error in run-time

```
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at slick.lifted.AbstractTable$$anonfun$indexes$2.apply(AbstractTable.scala:105)
	at slick.lifted.AbstractTable$$anonfun$indexes$2.apply(AbstractTable.scala:103)
	at scala.collection.TraversableViewLike$Mapped$$anonfun$foreach$2.apply(TraversableViewLike.scala:169)
	at scala.collection.TraversableViewLike$Filtered$$anonfun$foreach$4.apply(TraversableViewLike.scala:197)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.IndexedSeqLike$$anon$1.foreach(IndexedSeqLike.scala:52)
	at scala.collection.TraversableViewLike$Filtered$class.foreach(TraversableViewLike.scala:196)
	at scala.collection.mutable.IndexedSeqView$$anon$1.foreach(IndexedSeqView.scala:80)
	at scala.collection.TraversableViewLike$Mapped$class.foreach(TraversableViewLike.scala:168)
	at scala.collection.SeqViewLike$$anon$3.foreach(SeqViewLike.scala:197)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.ViewMkString$class.thisSeq(TraversableViewLike.scala:22)
	at scala.collection.SeqViewLike$AbstractTransformed.thisSeq(SeqViewLike.scala:37)
	at scala.collection.SeqViewLike$$anonfun$sortBy$1.apply(SeqViewLike.scala:266)
	at scala.collection.SeqViewLike$$anonfun$sortBy$1.apply(SeqViewLike.scala:266)
	at scala.collection.SeqViewLike$$anon$1.<init>(SeqViewLike.scala:195)
	at scala.collection.SeqViewLike$class.newForced(SeqViewLike.scala:195)
	at scala.collection.SeqViewLike$AbstractTransformed.newForced(SeqViewLike.scala:37)
	at scala.collection.SeqViewLike$class.sortBy(SeqViewLike.scala:266)
	at scala.collection.SeqViewLike$AbstractTransformed.sortBy(SeqViewLike.scala:37)
	at slick.lifted.AbstractTable.indexes(AbstractTable.scala:105)
	at slick.driver.JdbcStatementBuilderComponent$TableDDLBuilder.<init>(JdbcStatementBuilderComponent.scala:574)
	at slick.driver.PostgresDriver$TableDDLBuilder.<init>(PostgresDriver.scala:181)
	at com.github.tminglei.slickpg.ExPostgresDriver$TableDDLBuilder.<init>(ExPostgresDriver.scala:56)
	at com.github.tminglei.slickpg.ExPostgresDriver$class.createTableDDLBuilder(ExPostgresDriver.scala:18)
	at co.kernelnetworks.medstream.server.db.MyPostgresDriver$.createTableDDLBuilder(MyPostgresDriver.scala:76)
	at co.kernelnetworks.medstream.server.db.MyPostgresDriver$.createTableDDLBuilder(MyPostgresDriver.scala:76)
	at slick.driver.JdbcProfile$class.buildTableSchemaDescription(JdbcProfile.scala:40)
	at co.kernelnetworks.medstream.server.db.MyPostgresDriver$.buildTableSchemaDescription(MyPostgresDriver.scala:76)
	at co.kernelnetworks.medstream.server.db.MyPostgresDriver$.buildTableSchemaDescription(MyPostgresDriver.scala:76)
	at slick.profile.RelationalProfile$TableQueryExtensionMethods.schema(RelationalProfile.scala:62)
	at co.kernelnetworks.medstream.server.db.PostgresTables$class.$init$(PostgresTables.scala:176)
	at co.kernelnetworks.medstream.server.db.DBManager$.<init>(DBManager.scala:98)
	at co.kernelnetworks.medstream.server.db.DBManager$.<clinit>(DBManager.scala)
	... 2 more
Caused by: scala.MatchError: Apply Function ->> (of class slick.ast.Apply)
	at slick.lifted.ForeignKey$.slick$lifted$ForeignKey$$f$1(Constraint.scala:56)
	at slick.lifted.ForeignKey$.linearizeFieldRefs(Constraint.scala:61)
	at slick.lifted.AbstractTable.index(AbstractTable.scala:100)
	at co.kernelnetworks.medstream.server.db.PostgresTables$ArticleRow.idx_doi(PostgresTables.scala:132)
	... 41 more
```

Is it possible to do in type-safe manner ?

**Comment by tminglei** [comment]
Hi @cppexpert, `slick` didn't support function index yet.

**Comment by cppexpert** [comment]
@tminglei Could you please tell me what class of Slick source would you modify to add this feature ?

**Comment by tminglei** [comment]
Related codes exist in `AbstractTable.index(..)` of `AbstractTable.scala` and `TableDDLBuilder.createIndex(..)` of `JdbcStatementBuilderComponent.scala`.
