### ISSUE TITLE
PlainSQL - Option[ZonedDateTime] fails

### ISSUE THREAD

**Issue by Raymond26** [tminglei/slick-pg#281]
When i try to do a basic insert of an `Option[ZonedDateTime]` and it is None, i get the following error:

```
[info]   org.postgresql.util.PSQLException: Unknown Types value.
[info]   at org.postgresql.jdbc2.AbstractJdbc2Statement.setNull(AbstractJdbc2Statement.java:1220)
[info]   at org.postgresql.jdbc3.AbstractJdbc3Statement.setNull(AbstractJdbc3Statement.java:1490)
[info]   at org.postgresql.jdbc4.AbstractJdbc4Statement.setNull(AbstractJdbc4Statement.java:85)
[info]   at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.setNull(HikariProxyPreparedStatement.java)
[info]   at slick.jdbc.PositionedParameters.setNull(PositionedParameters.scala:16)
[info]   at com.github.tminglei.slickpg.utils.PlainSQLUtils$.com$github$tminglei$slickpg$utils$PlainSQLUtils$$internalSet(PlainSQLUtils.scala:46)
[info]   at com.github.tminglei.slickpg.utils.PlainSQLUtils$$anon$3.apply(PlainSQLUtils.scala:40)
[info]   at com.github.tminglei.slickpg.utils.PlainSQLUtils$$anon$3.apply(PlainSQLUtils.scala:39)
[info]   at slick.jdbc.SetParameter$$anon$1.apply(SetParameter.scala:9)
[info]   at slick.jdbc.SetParameter$$anon$1.apply(SetParameter.scala:7)
```
It works fine if the value is not empty.

My driver is defined like so, and im on 0.14.0
```
val plainAPI = DBPlainAPI
  object DBPlainAPI extends API
    with Date2DateTimePlainImplicits
```

Did I forget something?

**Comment by tminglei** [comment]
I just checked the source codes of postgres JDBC driver. That's because the driver didn't support `java.sql.Types.TIME_WITH_TIMEZONE` and `java.sql.Types.TIMESTAMP_WITH_TIMEZONE` yet, which were added in JDK 1.8.

I'll adjust the codes to resolve it ASAP.

**Comment by tminglei** [comment]
Resolved. You can help check it.
_Thanks! :-)_

**Comment by Raymond26** [comment]
That was super quick 😄  Thank you!
