### ISSUE TITLE
invalid input syntax for type timestamp with time zone

### ISSUE THREAD

**Issue by stonexx** [tminglei/slick-pg#282]
Hello,

Dependencies:
com.typesafe.slick:slick_2.11:3.1.1
com.github.tminglei:slick-pg_2.11:0.14.0
com.github.tminglei:slick-pg_joda-time_2.11:0.14.0
org.postgresql:postgresql:9.4-1201-jdbc41

Code:
```scala
import com.github.tminglei.slickpg._
import com.typesafe.config.ConfigFactory
import org.joda.time.{DateTime, Period}

import scala.concurrent.Await
import scala.concurrent.duration._

object Sample extends App {
  trait PostgresDriver extends ExPostgresDriver with PgDateSupportJoda { driver =>
    override val api: API = new API {}

    trait API extends super.API with DateTimeImplicits with JodaDateTimePlainImplicits
  }

  object PostgresDriver extends PostgresDriver

  import PostgresDriver.api._

  val db = Database.forConfig("test", config = ConfigFactory.parseString(
    """
      |test = {
      |  url = "jdbc:postgresql://127.0.0.1:5432/test"
      |  driver = org.postgresql.Driver
      |  connectionPool = disabled
      |  keepAliveConnection = true
      |}
    """.stripMargin
  ))
  try {
    val currentTimestamp = SimpleLiteral.apply[DateTime]("current_timestamp")

    val f = db.run(Query(currentTimestamp --- Period.days(1)).result)

    Await.result(f, Duration.Inf)
  } finally {
    db.close()
  }
}
```

Run results:
```shell
[info] Running Sample
[debug] s.j.J.statement - Preparing statement:
  select current_timestamp - ?
[error] (run-main-5) org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp with time zone: "P1D"
org.postgresql.util.PSQLException: ERROR: invalid input syntax for type timestamp with time zone: "P1D"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:413)
	at slick.jdbc.LoggingPreparedStatement$$anonfun$execute$5.apply$mcZ$sp(LoggingStatement.scala:83)
	at slick.jdbc.LoggingPreparedStatement$$anonfun$execute$5.apply(LoggingStatement.scala:83)
	at slick.jdbc.LoggingPreparedStatement$$anonfun$execute$5.apply(LoggingStatement.scala:83)
	at slick.jdbc.LoggingStatement.logged(LoggingStatement.scala:16)
	at slick.jdbc.LoggingPreparedStatement.execute(LoggingStatement.scala:83)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
	at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22)
	at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218)
	at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tminglei** [comment]
Well, currently the generated sql is `select current_timestamp - ?` for literal input, and after filled the value, it was changed to `select current_timestamp - 'P1D'`.
_But postgres won't convert `P1D` to an interval for us automatically for this case._

To fix it, we need to let slick/slick-pg generate the sql as `select current_timestamp - cast(? as interval)`.

**Comment by tminglei** [comment]
Just release slick-pg v0.14.1, which fixed the problem. Pls update your dependency to use it.
