### ISSUE TITLE
Aggregations in pg-slick are not compatible with groupBy

### ISSUE THREAD

**Issue by gedejong** [tminglei/slick-pg#289]
The aggregation functions in pg-slick are unfortunately not compatible with `groupBy` statements from Slick >3.0. In our code-base I've added a work-around, that might need to be introduced in pg-slick as well. The following code was added to `PgAggFuncSupportSuite`:

```
import slick.ast.Library.SqlAggregateFunction
import slick.ast.{BaseTypedType, TypedType}
import slick.lifted.FunctionSymbolExtensionMethods
```

```
  test("group by aggregates") {
    import FunctionSymbolExtensionMethods._
    val ArrayAgg = new SqlAggregateFunction("array_agg")

    implicit def singleColumnQueryExtensionMethods[B1 : BaseTypedType, C[_]](q: Query[Rep[B1], _, C]) = new Object {
      def arrayAgg(implicit tm: TypedType[List[B1]]): Rep[List[B1]] = ArrayAgg.column[List[B1]](q.toNode)
    }

    val sql1 = tabs.groupBy(t => t.name).map {
      case (name, tabs) => tabs.map(t => t.x).arrayAgg
    }

    println(sql1.result.statements.head)
  }
```

Do we want these and other SqlAggregateFunctions to be added to `PgAggFuncSupport`?

**Comment by tminglei** [comment]
I missed checking that. I'll resolve it asap.

**Comment by gedejong** [comment]
@tminglei I wouldn't mind implementing a PR for it :)

**Comment by tminglei** [comment]
I'm doing a test in `PgAggFuncSupportSuite.scala` using codes:
```scala
  test("used with groupBy") {
    import agg.PgAggFuncSupport.GeneralAggFunctions._

    implicit def shapedValueFromQuery[E, U, C[_]](q: Query[E, U, C]): E = q.shaped.value

    val sql = tabs.groupBy(_.bool).map {
      case (bool, group) => (bool, arrayAgg(group.name.?))
    }.result.statements.head
    println(s"sql: $sql")
  }
```
If it works, that will be great.

But I encountered exception:
```
No type for symbol col2 found in Vector[@t2<{x: Double', count: Int', y: Double', bool: Boolean', col2: String'}>]
slick.SlickException: No type for symbol col2 found in Vector[@t2<{x: Double', count: Int', y: Double', bool: Boolean', col2: String'}>]
	at slick.ast.Type$class.select(Type.scala:24)
	at slick.ast.CollectionType.select(Type.scala:132)
	at slick.ast.Select.buildType(Node.scala:530)
	at slick.ast.SimplyTypedNode$class.withInferredType(Node.scala:124)
	at slick.ast.Select.withInferredType(Node.scala:520)
	at slick.ast.Select.withInferredType(Node.scala:520)
	at slick.ast.Node$class.infer(Node.scala:90)
	at slick.ast.Select.infer(Node.scala:520)
...
```

_Any good idea?_

**Comment by tminglei** [comment]
Well, I realized I tried a wrong way. I finally resolved above problem, but then I encountered more problems. Because they are differently treated in slick.
So I'm going to turn to your way.

@gedejong Can you send me the PR, or let me take care of it?

**Comment by gedejong** [comment]
@tminglei I'd love to make a PR, since I think it's important to contribute back to OSS. I would implement the functions `val ArrayAgg = new SqlAggregateFunction("array_agg")` and others, which might not be optimal, since it duplicates the other code. I was really hoping there would be another way and tried a couple of different approaches as well... Seeing that you could not find a more elegant approach as well,  I will make a PR with the complete set of extra aggregations, starting somewhere next week. Unfortunately, I cannot start earlier because of time limitations.

**Comment by tminglei** [comment]
No problem. _Waiting for you! ;-)_

**Comment by tminglei** [comment]
@gedejong do you have time now? If you're still busy, I'm going to move it forward.

**Comment by gedejong** [comment]
@tminglei I looked at the problem quite a lot (two evenings) and thought of different approaches as well. The problem is obviously the hard-coded case matching in slick itself (on Apply). I feel bad to ruin your nice design by placing all these extra (similar and incompatible) aggregates next to it (plus, it still won't fix the statistical aggregates). Unfortunately, I'm still quite busy this week (couple of hectic releases). Please move it forward if you have time.

**Comment by tminglei** [comment]
@gedejong ok, I'll take care of it. _Thanks!_

**Comment by tminglei** [comment]
Well, it seems slick didn't support aggregates with other parameters in `groupBy`. Because of this, the statistical aggregates can't be supported by slick built-in logic.

We need find a way out.

**Comment by danishin** [comment]
@tminglei 
> Because of this, the statistical aggregates can't be supported by slick built-in logic.

Does this mean, general purpose aggregate functions work (`arrayAgg` specifically)?

Thanks.

**Comment by tminglei** [comment]
@danishin no, aggregate functions (e.g. `arrayAgg`) can't work with `groupBy` unless I resolved the issue.

**Comment by ski173** [comment]
@tminglei Has there been any update on this issue? I'm trying to learn how to use arrayAgg() at the moment but having some difficulties

**Comment by tminglei** [comment]
@ski173  not yet.

**Comment by SergeyZharikhin** [comment]
@tminglei, Hello, any updates on introducing `arrayAgg` function?

**Comment by tminglei** [comment]
@SergeyZharikhin No. In fact, I didn't find a good idea to move it forward.

**Comment by SergeyZharikhin** [comment]
@tminglei , so `arrayAgg` in `PgAggFuncSupport.GeneralAggFunctions` isn't working as expected?

**Comment by tminglei** [comment]
@SergeyZharikhin no.

**Comment by virusdave** [comment]
Any update on this issue?  Seems very useful and pretty important.

**Comment by fokot** [comment]
@davegurnell this is great thanks

**Comment by nebehr** [comment]
Can this idea be generalized for binary aggregate functions such as jsonb_object_agg?

**Comment by mberdyshev** [comment]
Does anybody know how to generalize the method for `Rep[Option[_]]`? Currently I get NPE if there's actually `None` inside.

**Comment by rudyjdira** [comment]
@mberdyshev did you find the solution to generalize to `Rep[Option[_]] `?

**Comment by mberdyshev** [comment]
@rudyjdira No, unfortunately.

**Comment by henry-macarthur** [comment]
@rudyjdira @mberdyshev Super late to the party, but I was able to get Rep[Option[B]] by defining a custom `AdvancedArrayJdbcType` for it. 

```scala 
private def fromString(string: String): Option[Int] = {
      if (string == "NULL") None
      else Some(string.toInt)
}

private def fromList(item: Option[Int]): String = {
      item match {
        case None => "NULL"
        case Some(i) => i.toString
      }
}

implicit val optionIntListMapper: DriverJdbcType[List[Option[Int]]] = new AdvancedArrayJdbcType[Option[Int]](
      "INTEGER",
      s => utils.SimpleArrayUtils.fromString[Option[Int]](fromString)(s).orNull,
      v => utils.SimpleArrayUtils.mkString[Option[Int]](fromList)(v),
).to(_.toList)
```
