### ISSUE TITLE
Support for JSON field with JsArray in root and complex type elements (not JsValue or simple String)

### ISSUE THREAD

**Issue by davojan** [tminglei/slick-pg#307]
In [examples for play-json](https://github.com/tminglei/slick-pg/blob/master/addons/play-json/src/test/scala/com/github/tminglei/slickpg/PgPlayJsonSupportSuite.scala) there are mappers for `JBean` and for `List[JsValue]`, but not for `List[JBean]`.

I've tried this:

``` scala
case class Phone(
  number: String,
  confirmed: Boolean = false
)
object Phone {
  implicit val writer = Json.writes[Phone]
  implicit val reader = Json.reads[Phone]
}

object ExtendedPostgresDriver extends PostgresDriver
  with PgPlayJsonSupport
  with PgArrayJdbcTypes
{
  def pgjson = "jsonb"

  override val api = new API with JsonImplicits {
    implicit val phoneJsonTypeMapper = MappedJdbcType.base[Phone, JsValue](Json.toJson(_), _.as[Phone])

    implicit val playJsonArrayTypeMapper =
      new AdvancedArrayJdbcType[Phone](pgjson,
        (s) ⇒ {
          println(s"record ${s}")
          SimpleArrayUtils.fromString[Phone](x ⇒ {
            println(s"token ${x}")
            Json.parse(x).as[Phone]
          })(s).orNull
        },
        (v) ⇒ SimpleArrayUtils.mkString[Phone](x ⇒ Json.stringify(Json.toJson(x)))(v)
      ).to(_.toList)
  }
}

case class Contact(id: Option[Int], phones: List[Phone])

class Contacts(tag: Tag) extends Table[ContactsProfile](tag, "contacts") {
  def id = column[Int]("id", O.PrimaryKey)
  def phones = column[List[Phone]]("phones")
  def * = (id.?, phones) <> (Contact.tupled, Contact.unapply)
}
```

It compiles well. But in runtime I got this when trying to read from the table:

```
record [{"number": "79999999991", "confirmed": true}, {"number": "79999999992", "confirmed": true}]

token {

com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: {; line: 1, column: 1])
 at [Source: {; line: 1, column: 3]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:458)
    at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:547)
    at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:555)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2265)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:601)
    at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:159)
    at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:108)
    at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:103)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3760)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2042)
    at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:226)
    at play.api.libs.json.Json$.parse(Json.scala:21)
    at models.ExtendedPostgresDriver$$anon$1$$anonfun$4$$anonfun$apply$1.apply(ExtendedPostgresDriver.scala:38)
    at models.ExtendedPostgresDriver$$anon$1$$anonfun$4$$anonfun$apply$1.apply(ExtendedPostgresDriver.scala:36)
    at com.github.tminglei.slickpg.utils.SimpleArrayUtils$$anonfun$fromString$1.apply(SimpleArrayUtils.scala:17)
    at com.github.tminglei.slickpg.utils.SimpleArrayUtils$$anonfun$fromString$1.apply(SimpleArrayUtils.scala:15)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:285)
    at com.github.tminglei.slickpg.utils.SimpleArrayUtils$.fromString(SimpleArrayUtils.scala:15)
    at models.ExtendedPostgresDriver$$anon$1$$anonfun$4.apply(ExtendedPostgresDriver.scala:39)
    at models.ExtendedPostgresDriver$$anon$1$$anonfun$4.apply(ExtendedPostgresDriver.scala:34)
    at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$AdvancedArrayJdbcType.getValue(PgArrayJdbcTypes.scala:91)
    at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$AdvancedArrayJdbcType.getValue(PgArrayJdbcTypes.scala:78)
    at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.getValue(PgArrayJdbcTypes.scala:117)
    at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.getValue(PgArrayJdbcTypes.scala:110)
    at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:26)
    at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
    at slick.relational.ProductResultConverter.read(ResultConverter.scala:56)
    at slick.relational.ProductResultConverter.read(ResultConverter.scala:46)
    at slick.relational.TypeMappingResultConverter.read(ResultConverter.scala:136)
    at slick.driver.JdbcInvokerComponent$QueryInvokerImpl.extractValue(JdbcInvokerComponent.scala:37)
    at slick.jdbc.StatementInvoker$$anon$1.extractValue(StatementInvoker.scala:67)
    at slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
    at slick.util.ReadAheadIterator$class.slick$util$ReadAheadIterator$$update(ReadAheadIterator.scala:34)
    at slick.util.ReadAheadIterator$class.hasNext(ReadAheadIterator.scala:40)
    at slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
    at slick.jdbc.Invoker$class.foreach(Invoker.scala:49)
    at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
    at slick.jdbc.Invoker$class.firstOption(Invoker.scala:24)
    at slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
    at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:57)
    at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:56)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
    at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

SQL type of `contacts.phones` field in postgres is `jsonb` (not `jsonb[]`).

So the question is: what is the right way to create type mapper for the list of typed objects (case classes)?

Thanks in advance!

**Comment by tminglei** [comment]
Hi @davojan I added test cases for your scenario, but didn't encounter your problem.

I don't know what exactly happened on your side, but you can check my codes to find out the different.

**Comment by davojan** [comment]
Thanks @tminglei!
I'll try again using your code and give a feedback.

**Comment by davojan** [comment]
Hi again @tminglei 

I've tried to use your example but still got the same issue with tokenizer - it extracts first curly brace instead of full JSON object.

But there are good news! :)

I figured out that using ``SimpleArrayUtils`` for JSON conversion is rather redundant and unnatural becase we already have play-json that cat do the job for us. So, here is simpler and workable (for me) version of your example:  

```scala
implicit val beanArrayTypeMapper =
  new AdvancedArrayJdbcType[JBean](pgjson,
    (s) => Json.parse(s).as[Seq[JBean]],
    (v) => Json.stringify(Json.toJson(v))
  ).to(_.toList)
```

For the moment I've tested only reading scenario. But I think writing should work as well.

I think this method should be shown in examples as more intuitive.

**Comment by tminglei** [comment]
Yeah, using play-json's built-in functions should be ok. But I still don't know why you failed.

**Comment by davojan** [comment]
Write case for my code above doesn't work with error:
```
ERROR: column "phones" is of type jsonb but expression is of type jsonb[]
```
So I finally got it! It was my misunderstanding and ambiguous example.

Your examples with lists assumes ``jsonb[]`` SQL type. But I have just ``jsonb`` with array in the root in terms of JSON (not postgres array type). So, the right way for me is much simpler:
```scala
implicit val beanListJsonTypeMapper = MappedJdbcType.base[List[JBean], JsValue](Json.toJson(_), _.as[List[JBean]])
```
And finally it works!

I think comments describing SQL-types for the columns could be added to the example to made it less ambiguous. And my example with bean-list would not be redundant too.

@tminglei thank you for your great work!

**Comment by tminglei** [comment]
Glad to hear that. You're welcome!
