### ISSUE TITLE
reactivemongo and play-json incompatibilities.

### ISSUE THREAD

**Issue by pramodkudapa** [tminglei/slick-pg#352]
Im using play-json libraries to be able to use jsonb column mapper for postgres support but its interfering with reactivemongo while parsing json values from mongo. How can I resolve this. Thanks.

**Comment by tminglei** [comment]
I don't understand your problem. Can you explain it more clearly?

**Comment by pramodkudapa** [comment]
Im working on a play-scala project which uses slick-pg dependency, and I have imported your play-Json dependency for using jsonb columns in my pg-table. But I'm also using play-reactivemongo 2.5 version for mongo db parsing. This tminglei-play-Json library is causing incompatibility and is blocking reactivemongo and unable to read jsboolean and jsArray fields from my Json in mongodb. 
Can you help me resolve this. Thanks.

**Comment by tminglei** [comment]
Well, I mean, can you provide more details?
_A reproducible sample project is good._

**Comment by pramodkudapa** [comment]
my  reactivemongo code to fetch docs from collection =>
`collection.find(selector).one[JsValue]`

-dependencies used : 
-> play  version : "com.typesafe.play" % "sbt-plugin" % "2.5.13")
-> ```
libraryDependencies ++= Seq(
  cache,
  ws,
  specs2 % Test,
  "com.typesafe.play.modules" %% "play-modules-redis" % "2.5.0",
  "org.reactivemongo" %% "play2-reactivemongo" % "0.11.14",
  "io.igl" %% "jwt" % "1.2.0",
  "mysql" % "mysql-connector-java" % "5.1.34",
  "org.postgresql" % "postgresql" % "42.1.1",
  "com.github.tminglei" %% "slick-pg" % "0.15.0",
  "com.github.tminglei" %% "slick-pg_play-json" % "0.15.0"
)
```
From my understanding there is a version incompatibility with play-json 2.6.0-RC1 and reactivemongo.

-> my problem is very much similar to this below one, check this link for better understanding.
https://groups.google.com/forum/#!topic/play-framework/3YAMZbe5nRY


The exception is raised when querying mongodb:
there is a problem with parsing JsArray and JsBoolean, JsString seems to be working fine, as in String and integer fields are easily read by reactivemongo but not boolean or List() fields.


ERROR STACKTRACE:
`java.lang.NoSuchMethodError: play.api.libs.json.JsArray.<init>(Lscala/collection/Seq;)V
	at 
reactivemongo.play.json.commands.JSONAggregationImplicits$AggregateWriter$.writes(aggregate.scala:63)
	at reactivemongo.play.json.commands.JSONAggregationImplicits$AggregateWriter$.writes(aggregate.scala:58)
	at reactivemongo.play.json.JSONSerializationPack$.serialize(package.scala:725)
	at reactivemongo.play.json.JSONSerializationPack$.serialize(package.scala:703)
	at reactivemongo.api.SerializationPack.serializeAndWrite(serializationpack.scala:27)
	at reactivemongo.api.SerializationPack.serializeAndWrite$(serializationpack.scala:27)
	at reactivemongo.play.json.JSONSerializationPack$.serializeAndWrite(package.scala:703)
	at reactivemongo.api.commands.Command$$anon$2.cursor(commands.scala:175)
	at reactivemongo.api.commands.Command$$anon$2.cursor(commands.scala:153)
	at reactivemongo.api.commands.Command$CommandWithPackRunner.withResponse(commands.scala:227)
	at reactivemongo.api.collections.GenericCollectionWithCommands.runWithResponse(genericcollection.scala:70)
	at reactivemongo.api.collections.GenericCollectionWithCommands.runWithResponse$(genericcollection.scala:70)
	at reactivemongo.play.json.collection.JSONCollection.runWithResponse(collection.scala:372)
	at reactivemongo.api.collections.GenericCollection.aggregate(genericcollection.scala:568)
	at reactivemongo.api.collections.GenericCollection.aggregate$(genericcollection.scala:561)
	at reactivemongo.play.json.collection.JSONCollection.aggregate(collection.scala:372)
	at eu.macq.m3.gero.toiler.services.MongoServiceImpl.$anonfun$getRatRunningConfig$1(mongo.scala:197)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

**Comment by pramodkudapa** [comment]
error stacktrace : 
`java.lang.InstantiationError: play.api.libs.json.JsBoolean
	at reactivemongo.play.json.BSONFormats$BSONBooleanFormat$$anonfun$14.applyOrElse(package.scala:210)
	at reactivemongo.play.json.BSONFormats$BSONBooleanFormat$$anonfun$14.applyOrElse(package.scala:209)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at reactivemongo.play.json.BSONFormats$class.toJSON(package.scala:411)
	at reactivemongo.play.json.BSONFormats$.toJSON(package.scala:82)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$$lessinit$greater$2.apply(package.scala:151)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$$lessinit$greater$2.apply(package.scala:151)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$json$1.apply(package.scala:148)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$json$1.apply(package.scala:148)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
	at scala.collection.generic.Growable$class.loop$1(Growable.scala:54)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
	at scala.collection.mutable.AbstractMap.$plus$plus$eq(Map.scala:80)
	at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:48)
	at play.api.libs.json.JsObject$.apply(JsValue.scala:205)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat.json(package.scala:148)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$6.applyOrElse(package.scala:133)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$6.applyOrElse(package.scala:132)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at reactivemongo.play.json.BSONFormats$class.toJSON(package.scala:411)
	at reactivemongo.play.json.BSONFormats$.toJSON(package.scala:82)
	at reactivemongo.play.json.JSONSerializationPack$.readFromBuffer(package.scala:486)
	at reactivemongo.play.json.JSONSerializationPack$.readFromBuffer(package.scala:437)
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:28)
	at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(package.scala:437)
	at reactivemongo.core.protocol.ReplyDocumentIterator$$anon$1.next(protocol.scala:377)
	at reactivemongo.api.DefaultCursor$Impl$$anonfun$6.apply(cursor.scala:646)
	at scala.util.Try$.apply(Try.scala:192)
`

**Comment by tminglei** [comment]
Sorry, too busy these days. I'll resolve it later.

**Comment by tminglei** [comment]
Well, I can't find out the version conflict issue from the code snippet. I need a reproducible project to dig in.
