### ISSUE TITLE
Composite Types containing strings with parenthesis cannot be parsed

### ISSUE THREAD

**Issue by zgrannan** [tminglei/slick-pg#362]
An error is returned when retrieving a row that contains a composite type that has a string member and also includes parenthesis in the string. For example, assuming a schema as follows:

```scala
class TestTable1(tag: Tag) extends Table[TestBean1](tag, "CompositeTest1") {
  def id = column[Long]("id")
  def comps = column[List[Composite3]]("comps")

  def * = (id,comps) <> (TestBean1.tupled, TestBean1.unapply)
}

case class TestBean1(
  id: Long,
  comps: List[Composite3]
)

case class Composite3(
  name: Option[String] = None,
  code: Option[Int] = None,
  num: Option[Int] = None,
  bool: Option[Boolean] = None
) extends Struct
val record = TestBean1(114, List(Composite3(Some("Word1 (Word2)"))))
```

Inserting `record` works fine, but when attempting to retrieve the following error occurs:

```
[info]   java.lang.IllegalArgumentException: WRONG token type: Chunk(Word1 )
[info]   at com.github.tminglei.slickpg.utils.PgTokenHelper$.getChildren(PgTokenHelper.scala:80)
[info]   at com.github.tminglei.slickpg.PgCompositeSupportUtils$CompositeConverter.fromToken(PgCompositeSupport.scala:128)
[info]   at com.github.tminglei.slickpg.PgCompositeSupportUtils$SeqConverter$$anonfun$fromToken$1.apply(PgCompositeSupport.scala:158)
[info]   at com.github.tminglei.slickpg.PgCompositeSupportUtils$SeqConverter$$anonfun$fromToken$1.apply(PgCompositeSupport.scala:158)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[info]   at scala.collection.immutable.List.map(List.scala:296)
[info]   at com.github.tminglei.slickpg.PgCompositeSupportUtils$SeqConverter.fromToken(PgCompositeSupport.scala:158)
```
A gist containing the failing test case added to PgCompositeSupportSuite is here: https://gist.github.com/zgrannan/1f0165214144c5fd81de3dddef35e3bf

**Comment by tminglei** [comment]
Hi @zgrannan, fixed, pls help check. _Thanks!_

**Comment by zgrannan** [comment]
The fixed worked, thanks a lot!
