### ISSUE TITLE
Composite types containing empty strings parsed incorrectly

### ISSUE THREAD

**Issue by zgrannan** [tminglei/slick-pg#363]
An error is returned when retrieving a row that contains a composite type that has a string member that contains an empty String. For example, assuming a schema as follows:

```scala
class TestTable1(tag: Tag) extends Table[TestBean1](tag, "CompositeTest1") {
  def id = column[Long]("id")
  def comps = column[List[Composite3]]("comps")

  def * = (id,comps) <> (TestBean1.tupled, TestBean1.unapply)
}

case class TestBean1(
  id: Long,
  comps: List[Composite3]
)

case class Composite1(
  id: Long,
  txt: String,
  date: Timestamp,
  tsRange: Option[Range[Timestamp]]
) extends Struct

case class Composite3(
  name: Option[String] = None,
  code: Option[Int] = None,
  num: Option[Int] = None,
  bool: Option[Boolean] = None
) extends Struct
val record = TestBean1(114, List(Composite3(Some(""))))
```

When retrieving the record from the DB , `name` has value `Some(")` instead of `Some()`

If the empty string is not the first member of the composite type (such as `Composite1`), an error occurs when retrieving the inserted row:

```
[info]   java.lang.StringIndexOutOfBoundsException: String index out of range: -1
[info]   at java.lang.String.substring(String.java:1960)
[info]   at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1(PgTokenHelper.scala:229)
[info]   at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1$adapted(PgTokenHelper.scala:166)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:156)
[info]   at com.github.tminglei.slickpg.utils.PgTokenHelper$.grouping(PgTokenHelper.scala:166)
[info]   at com.github.tminglei.slickpg.PgCompositeSupportUtils.$anonfun$mkCompositeFromString$1(PgCompositeSupport.scala:55)
[info]   at com.github.tminglei.slickpg.utils.PgCommonJdbcTypes$GenericJdbcType.getValue(PgCommonJdbcTypes.scala:22)
[info]   at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:26)
[info]   at slick.jdbc.SpecializedJdbcResultConverter$$anon$1.read(SpecializedJdbcResultConverters.scala:24)
[info]   at slick.relational.ProductResultConverter.read(ResultConverter.scala:53)
```

A gist containing the failing test cases added to PgCompositeSupportSuite is here: 
https://gist.github.com/zgrannan/d866aae087bcde3fb5d893388224ecee

**Comment by tminglei** [comment]
Hi @zgrannan fixed, pls help check. _Thanks!_
