### ISSUE TITLE
Cant use source code generator when jsonb column has default value

### ISSUE THREAD

**Issue by mguzowski-jlabs** [tminglei/slick-pg#384]
Hi

Im trying to use code generator for jsonb colmn with default value '{}'.
I get such error:

[error] (run-main-5) slick.SlickException: Could not parse default value Some('{}'::jsonb) for column n_gram.ngrams of type String, meta data: MColumn(MQName(public.n_gram),ngrams,1111,jsonb,Some(2147483647),Some(0),10,Some(false),None,Some('{}'::jsonb),2147483647,8,Some(false),None,None,Some(false))
[error] slick.SlickException: Could not parse default value Some('{}'::jsonb) for column n_gram.ngrams of type String, meta data: MColumn(MQName(public.n_gram),ngrams,1111,jsonb,Some(2147483647),Some(0),10,Some(false),None,Some('{}'::jsonb),2147483647,8,Some(false),None,None,Some(false))
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:271)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:280)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$columns$1(JdbcModelBuilder.scala:162)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
[error]         at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$6(JdbcModelBuilder.scala:95)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.immutable.List.map(List.scala:295)
[error]         at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$4(JdbcModelBuilder.scala:95)
[error]         at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
[error]         at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContext$1(BasicBackend.scala:147)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error]         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] Caused by: scala.MatchError: ('{}'::jsonb,String) (of class scala.Tuple2)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.$anonfun$default$1(JdbcModelBuilder.scala:216)
[error]         at scala.Option.map(Option.scala:146)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.default(JdbcModelBuilder.scala:213)
[error]         at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2.super$default(PostgresProfile.scala:110)
[error]         at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2.$anonfun$default$2(PostgresProfile.scala:110)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at slick.jdbc.PostgresProfile$ModelBuilder$$anon$2.default(PostgresProfile.scala:109)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.$anonfun$defaultColumnOption$2(JdbcModelBuilder.scala:253)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.defaultColumnOption(JdbcModelBuilder.scala:253)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.convenientDefault(JdbcModelBuilder.scala:262)
[error]         at slick.jdbc.JdbcModelBuilder$ColumnBuilder.model(JdbcModelBuilder.scala:280)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.$anonfun$columns$1(JdbcModelBuilder.scala:162)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:162)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:162)
[error]         at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:160)
[error]         at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$6(JdbcModelBuilder.scala:95)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error]         at scala.collection.immutable.List.foreach(List.scala:389)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error]         at scala.collection.immutable.List.map(List.scala:295)
[error]         at slick.jdbc.JdbcModelBuilder.$anonfun$buildModel$4(JdbcModelBuilder.scala:95)
[error]         at slick.dbio.DBIOAction.$anonfun$map$1(DBIOAction.scala:43)
[error]         at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContext$1(BasicBackend.scala:147)
[error]         at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
[error]         at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error]         at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at sbt.Run$.executeTrapExit(Run.scala:120)
[error]         at sbt.Run.run(Run.scala:73)
[error]         at sbt.BuildExtra.$anonfun$fullRunTask$3(Defaults.scala:3166)
[error]         at sbt.BuildExtra.$anonfun$fullRunTask$3$adapted(Defaults.scala:3164)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)

Can anyone help me with that ?

**Comment by tminglei** [comment]
@mguzowski-jlabs I found the related codes in `PostgresProfile#ModelBuilder.createColumnBuilder().default()` like this:
```scala
trait PostgresProfile extends JdbcProfile {
...
  class ModelBuilder(mTables: Seq[MTable], ignoreInvalidDefaults: Boolean)(implicit ec: ExecutionContext) extends JdbcModelBuilder(mTables, ignoreInvalidDefaults) {
...
    override def createColumnBuilder(tableBuilder: TableBuilder, meta: MColumn): ColumnBuilder = new ColumnBuilder(tableBuilder, meta) {
...
      override def default = meta.columnDef.map((_,tpe)).collect{
        case ("true","Boolean")  => Some(Some(true))
        case ("false","Boolean") => Some(Some(false))
        case (TextPattern(str),"String") => Some(Some(str))
...
}
```

So you can try as this:
```scala
trait YourCustomizedPostgresProfile .. {
...
  class ModelBuilder(..) extends super.ModelBuilder(..) {
...
    override def createColumnBuilder(..): ColumnBuilder = new ColumnBuilder(..) {
...
      override def default = meta.columnDef.map((_,tpe)).collect{
        case (str, "jsonb") => Some(Some(Json.parse(str)))
        ...
      }
    }
  }
}
```
You may have to copy and paste some duplicated codes from `PostgresProfile` to `YourCustomizedPostgresProfile`, since they didn't define an independent `ModelBuilder` in `PostgresProfile`.

_Good luck!! And any question you can let me know._

**Comment by mguzowski-jlabs** [comment]
shouldn't there be a way to easliy inject into slick some additional strategies, types or behavior (e.g. code generation behavior) ?

I already wrote some extensions to profile, overriding some classes or methods.. Im afraid that next bigger release of slick would force me to write this code once again, because any slick refactoring may break it....

**Comment by tminglei** [comment]
@mguzowski-jlabs above is the way to inject your customized codes into slick.

If the scala `json` type was determined, I can inject it ahead. But it's up to you, so you had to do it yourself.
