### ISSUE TITLE
java.lang.AbstractMethodError when trying to load profile

### ISSUE THREAD

**Issue by missingfaktor** [tminglei/slick-pg#387]
Hey, all.

I have a database profile very similar to the one in the README.

```scala
package utils.slick

import com.github.tminglei.slickpg._
import slick.basic.Capability
import slick.jdbc.JdbcCapabilities

object DgPostgreSqlProfile
  extends ExPostgresProfile
    with PgArraySupport
    with PgDate2Support
    with PgRangeSupport
    with PgDateSupportJoda
    with PgCirceJsonSupport {

  def pgjson: String = {
    "JSONB"
  }

  override protected def computeCapabilities: Set[Capability] = {
    super.computeCapabilities + JdbcCapabilities.insertOrUpdate
  }

  override val api = {
    CustomApi
  }

  object CustomApi
    extends API
      with ArrayImplicits
      with DateTimeImplicits
      with JsonImplicits
      with RangeImplicits

}
```

When I run `sbt:console` and try to load up this profile, I get a `java.lang.AbstractMethodError`:

```
scala> import utils.slick.DgPostgreSqlProfile
import utils.slick.DgPostgreSqlProfile

scala> val p = utils.slick.DgPostgreSqlProfile
16:13:53.286 [INFO ] u.s.DgPostgreSqlProfile -  >>> binding uuid -> java.util.UUID  (run-main-6)
16:13:53.320 [INFO ] u.s.DgPostgreSqlProfile -  >>> binding text -> java.lang.String  (run-main-6)
16:13:53.321 [INFO ] u.s.DgPostgreSqlProfile -  >>> binding bool -> Boolean  (run-main-6)
java.lang.AbstractMethodError: Method utils/slick/DgPostgreSqlProfile$CustomApi$.slick$basic$BasicProfile$API$_setter_$Database_$eq(Ljava/lang/Object;)V is abstract
  at utils.slick.DgPostgreSqlProfile$CustomApi$.slick$basic$BasicProfile$API$_setter_$Database_$eq(DgPostgreSqlProfile.scala)
  at slick.basic.BasicProfile$API.$init$(BasicProfile.scala:44)
  at utils.slick.DgPostgreSqlProfile$CustomApi$.<init>(DgPostgreSqlProfile.scala:28)
  at utils.slick.DgPostgreSqlProfile$CustomApi$.<clinit>(DgPostgreSqlProfile.scala)
  at utils.slick.DgPostgreSqlProfile$.<init>(DgPostgreSqlProfile.scala:24)
  at utils.slick.DgPostgreSqlProfile$.<clinit>(DgPostgreSqlProfile.scala)
  ... 38 elided
```

I am using Scala v2.12.4, slick 3.2.1, slick-pg 0.16.0, and org.postgresql:postgresql v42.2.1.

**Comment by missingfaktor** [comment]
Weird. Converting to a `trait` + `object` pair fixed the problem.

**Comment by tminglei** [comment]
Yeah, it should be `trait` + `object`. _It's a scala issue, I don't know why._

**Comment by missingfaktor** [comment]
@henricook This works for me:

```scala
trait DgPostgreSqlProfile extends ... {
 ...
}

object DgPostgreSqlProfile extends DgPostgreSqlProfile
```
