### ISSUE TITLE
Cannot check if array contains UUID

### ISSUE THREAD

**Issue by A23salkdjfdslkfj** [tminglei/slick-pg#393]
I am getting this error when using the `any` syntax for arrays.  I can't figure out what the problem is after a few hours.  Was wondering if you can point me to the right direction... 

` ERROR: syntax error at or near "any"
instructorJVM   Position: 287
instructorJVM org.postgresql.util.PSQLException: ERROR: syntax error at or near "any"
instructorJVM   Position: 287
instructorJVM 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2427)
instructorJVM 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2169)
instructorJVM 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
instructorJVM 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
instructorJVM 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
instructorJVM 	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
instructorJVM 	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
instructorJVM 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
instructorJVM 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
instructorJVM 	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:38)
instructorJVM 	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
instructorJVM 	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
instructorJVM 	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
instructorJVM 	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
instructorJVM 	at slick.jdbc.Invoker.firstOption(Invoker.scala:23)
instructorJVM 	at slick.jdbc.Invoker.firstOption$(Invoker.scala:21)
instructorJVM 	at slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:15)
instructorJVM 	at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:57)
instructorJVM 	at slick.jdbc.StreamingInvokerAction$HeadOptionAction.run(StreamingInvokerAction.scala:56)
instructorJVM 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:242)
instructorJVM 	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:242)
instructorJVM 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
instructorJVM 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
instructorJVM 	at java.lang.Thread.run(Thread.java:748)
instructorJVM 2018-03-22 15:32:06.284 [default-akka.actor.default-dispatcher-11] ERROR akka.actor.ActorSystemImpl.$anonfun$applyOrElse$1(Slf4jLogger.scala:69) - Error during processing of request: 'Slick error'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.`

This is the query: `query.filter(_.groupInstructors.any === instructor)`
This is the column array: https://screenshots.firefox.com/rk80ZvCsv2dnelzg/0.0.0.0

These are my type mappers: 

`case class SampleID(value: UUID) extends ID`

```
class IdentityJdbcType[ID <: Identity](adapter: IdentityAdapter[ID])(implicit override val classTag: ClassTag[ID])
    extends DriverJdbcType[ID] {
    self ⇒

    override val hasLiteralForm = true

    override val sqlType: Int = java.sql.Types.OTHER

    override def sqlTypeName(sym: Option[FieldSymbol]) = "UUID"

    override def setValue(v: ID, p: PreparedStatement, idx: Int) = p.setObject(idx, v.value, sqlType)

    override def getValue(r: ResultSet, idx: Int) = adapter.create(r.getObject(idx).asInstanceOf[UUID])

    override def valueToSQLLiteral(value: ID) = "'" + value.value + "'"

    override def updateValue(v: ID, r: ResultSet, idx: Int) = r.updateObject(idx, v.value)
  }

  class IdentityArrayJdbcType[ID <: Identity](adapter: IdentityAdapter[ID],
                                              zero: Seq[ID] = null.asInstanceOf[Seq[ID]])
                                             (implicit override val classTag: ClassTag[Seq[ID]], ctag: ClassTag[ID])
    extends DriverJdbcType[Seq[ID]] {
    self ⇒

    override val hasLiteralForm: Boolean = false
    override val sqlType       : Int     = java.sql.Types.ARRAY

    override def sqlTypeName(size: Option[FieldSymbol]): String = s"UUID []"

    override def valueToSQLLiteral(v: Seq[ID]) = {
      if (v eq null) "NULL" else s"'${buildArrayStr(v)}'"
    }

    override def getValue(r: ResultSet, idx: Int): Seq[ID] = {
      if (r.wasNull()) zero else {
        r.getArray(idx).asInstanceOf[Array[UUID]].map(v ⇒ adapter.create(v))
      }
    }

    override def setValue(v: Seq[ID], p: PreparedStatement, idx: Int): Unit = {
      p.setArray(idx, mkArray(v))
    }

    override def updateValue(v: Seq[ID], r: ResultSet, idx: Int): Unit = {
      r.updateArray(idx, mkArray(v))
    }

    protected def buildArrayStr(v: Seq[ID]): String = {
      createString {
        v match {
          case null ⇒ Null
          case list ⇒
          val token = GroupToken(Open("{") +: list.map {
            case null ⇒ Null
            case i    ⇒ Chunk(i.toString)
          } :+ Close("}"))

          logger.info(s"Token value [${token.toString()}]")
          token
        }
      }
    }

    private def mkArray(v: Seq[ID]): java.sql.Array = {
      utils.SimpleArrayUtils.mkArray[ID](buildArrayStr)(sqlBaseType = "UUID", v)
    }
  }
```

**Comment by A23salkdjfdslkfj** [comment]
It seems like reversing the filter params works?

`query.filter(instructor === _.groupInstructors.any)` // works
`query.filter(_.groupInstructors.any === instructor)` // doesn't work
