### ISSUE TITLE
java.util.NoSuchElementException: head of empty list in PgTokenHelper

### ISSUE THREAD

**Issue by bryanmau1** [tminglei/slick-pg#410]
I'm running Scala 2.12 against Slick 2.1 with slick-pg 0.8.6
I'd like to have a column that is a list `Endpoints` where an `Endpoint` is a case class with a json formatter.  Here's my mapper:
```
    implicit val endpointsArrayTypeMapper = {
      new AdvancedArrayJdbcType[AddOrRemoveEndpoint]("jsonb",
        (json) => {
          SimpleArrayUtils.fromString[AddOrRemoveEndpoint] { jsonStr =>
            Json.parse(jsonStr).as[AddOrRemoveEndpoint]
          }(json).orNull
        },
        (endpoints) => SimpleArrayUtils.mkString[AddOrRemoveEndpoint] { endpoint =>
          Json.stringify(Json.toJson(endpoint))
        }(endpoints)
      ).to(_.toList)
    }
```
I also have.
```
case class AddOrRemoveEndpoint(added: Boolean, endpoint: Endpoint)
object AddOrRemoveEndpoint {
  implicit val addOrRemoveEndpointFormat = Json.format[AddOrRemoveEndpoint]
}
```
And then my table definition looks like 
`def addOrRemoveEndpoints: Column[Option[List[AddOrRemoveEndpoint]]] = column[Option[List[AddOrRemoveEndpoint]]]("add_or_remove_endpoints")`

When I add a row and put in an `endpoint`, my database looks like this locally. 
`[u'{"added":false,"endpoint":{"method":"GET","url":"/api/settings"}}']`

But as soon as I try to read, it throws this error
```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:428)
	at scala.collection.immutable.Nil$.head(List.scala:425)
	at scala.collection.mutable.Stack.top(Stack.scala:133)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$7(PgTokenHelper.scala:255)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$7$adapted(PgTokenHelper.scala:249)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1(PgTokenHelper.scala:249)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1$adapted(PgTokenHelper.scala:165)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.grouping(PgTokenHelper.scala:165)
	at com.github.tminglei.slickpg.utils.SimpleArrayUtils$.fromString(SimpleArrayUtils.scala:11)
```

What am I doing wrong?  Or, could this be a bug for this particular version of slick-pg?

**Comment by bryanmau1** [comment]
I wonder if this is related to https://github.com/tminglei/slick-pg/issues/409.
I worked around this by encoding my JSON to base64 and then it worked.

**Comment by tminglei** [comment]
@bryanmau1 #409 only related to master branch.

**Comment by tminglei** [comment]
@bryanmau1 #409 only related to branch master.
To fix it, seems we need apply #409 fix to branch slick2.

Well, why are you guys still stick to so old version of slick?
