### ISSUE TITLE
NoSuchMethodError org.postgresql.jdbc.PgConnection.createArrayOf

### ISSUE THREAD

**Issue by kolapkardhaval** [tminglei/slick-pg#411]
@tminglei , I am getting this below error in 0.16.1

Exception in thread "db-17" java.lang.NoSuchMethodError: org.postgresql.jdbc.PgConnection.createArrayOf(Ljava/lang/String;Ljava/lang/Object;)Ljava/sql/Array;
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.mkArray(PgArrayJdbcTypes.scala:42)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.setValue(PgArrayJdbcTypes.scala:31)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.setValue(PgArrayJdbcTypes.scala:13)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.setValue(PgArrayJdbcTypes.scala:107)
	at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.setValue(PgArrayJdbcTypes.scala:98)
	at slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:16)
	at slick.jdbc.BaseResultConverter.set(JdbcResultConverter.scala:8)
	at slick.relational.ProductResultConverter.set(ResultConverter.scala:68)
	at slick.relational.ProductResultConverter.set(ResultConverter.scala:43)
	at slick.relational.TypeMappingResultConverter.set(ResultConverter.scala:135)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$11(JdbcActionComponent.scala:509)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedInsertStatement(JdbcBackend.scala:393)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedInsertStatement$(JdbcBackend.scala:390)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:448)
	at slick.jdbc.JdbcActionComponent$ReturningInsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:650)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:507)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:30)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:27)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tminglei** [comment]
@kolapkardhaval can you provide more details? I need the whole env info.

**Comment by monkeymantra** [comment]
Yeah, this is something you can solve with mvn dependency:tree. It's just a bad org.postgresql:postgresql version (read: old, not 42.whatever) being pulled in. I got here googling this same error.

**Comment by monkeymantra** [comment]
I have very similar code in another project that does *not* get this error. I'm perplexed.

**Comment by monkeymantra** [comment]
Slick version 3.2.3, otherwise:

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.2</version>
        </dependency>
        <dependency>
            <groupId>com.github.tminglei</groupId>
            <artifactId>slick-pg_${scala.compat.version}</artifactId>
            <version>0.16.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.tminglei</groupId>
            <artifactId>slick-pg_joda-time_${scala.compat.version}</artifactId>
            <version>0.16.1</version>
        </dependency>
    </dependencies>

**Comment by monkeymantra** [comment]
scala 2.11

**Comment by tminglei** [comment]
Well, I'm also confused. I can't find obvious issues in it.
Give me a reproducable sample project, pls, to allow me to dig into.

**Comment by monkeymantra** [comment]
So, I wasn't able to reproduce it in a separate repository without including proprietary stuff, but here's what happens: Basically, it works in the persistence module I make. But when I set that persistence module, which depends on 42.2.2 of org.postgresql:postgresql, the module attempting to use it somehow gets forced, by the module itself, to use 9.4.1212?! even though that modeling-service-persistence itself uses 42.2.2. Totally stupid.

By adding an exclude for org.postgresql:postgresql to the modeling-service-persistence dependency, and explicitly adding a dependency to 42.2.2 to the server module, which is stupid and shouldn't have to be done, I can fix the problem.

[INFO] com.mycompany:modeling-service-server:jar:1.0-SNAPSHOT
[INFO] \- com.mycompany:modeling-service-persistence:jar:1.0-SNAPSHOT:compile
[INFO]    \- org.postgresql:postgresql:jar:9.4.1212.jre7:compile

**Comment by tminglei** [comment]
@monkeymantra yes, that's it, you resolved my confusion.
