### ISSUE TITLE
SimpleArrayUtils.fromString fails when parsing some valid expression 

### ISSUE THREAD

**Issue by klpx** [tminglei/slick-pg#419]
**DESCRIPTION:**

SimpleArrayUtils.fromString fails when parses quoted element with the first character is closing round bracket at the beginning.

**STEPS TO REPRODUCE:**

```
SimpleArrayUtils.fromString(identity)("""{")"}""")
```

**EXPECTED RESULT:**

`Seq(")")`

**ACTUAL RESULT:**

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1960)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1(PgTokenHelper.scala:232)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.$anonfun$grouping$1$adapted(PgTokenHelper.scala:166)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at com.github.tminglei.slickpg.utils.PgTokenHelper$.grouping(PgTokenHelper.scala:166)
	at com.github.tminglei.slickpg.utils.SimpleArrayUtils$.fromString(SimpleArrayUtils.scala:13)
	... (scratch trace)
(no root cause)
```

**NOTICE:**

Cases `{)}` and `{"prefix)"}` works fine. Cases `{"other",")"}` and `{")suffix"}` also fails.

**SETUP:**

No setup needed.

**Comment by tminglei** [comment]
@klpx ok, I'll fix it ASAP.

**Comment by tminglei** [comment]
Fixed, pls help check.

**Comment by klpx** [comment]
WOW! So fast!
Looks good! Works well in my source scratch

**Comment by tminglei** [comment]
@klpx released, you can update your dependency to use it. :-)

**Comment by klpx** [comment]
Thanks you!
![So fast](https://media.giphy.com/media/lRnUWhmllPI9a/giphy.gif)
