### ISSUE TITLE
java.lang.ClassCastException: com.sun.proxy.$Proxy2 cannot be cast to org.postgresql.jdbc.PgConnection

### ISSUE THREAD

**Issue by pantelissd** [tminglei/slick-pg#441]
Hi @tminglei I am having a similar issue with version 0.17.0 and slick 3.2.3

`java.lang.ClassCastException: com.sun.proxy.$Proxy2 cannot be cast to org.postgresql.jdbc.PgConnection
          at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.mkArray(PgArrayJdbcTypes.scala:42)
          at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.setValue(PgArrayJdbcTypes.scala:31)
          at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$SimpleArrayJdbcType.setValue(PgArrayJdbcTypes.scala:13)
          at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.setValue(PgArrayJdbcTypes.scala:107)
          at com.github.tminglei.slickpg.array.PgArrayJdbcTypes$WrappedConvArrayJdbcType.setValue(PgArrayJdbcTypes.scala:98)
          at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.$anonfun$expr$14(JdbcStatementBuilderComponent.scala:408)
          at slick.jdbc.JdbcStatementBuilderComponent$QueryBuilder.$anonfun$expr$14$adapted(JdbcStatementBuilderComponent.scala:406)
          at slick.util.SQLBuilder.$anonfun$build$2(SQLBuilder.scala:39)
          at slick.util.SQLBuilder.$anonfun$build$2$adapted(SQLBuilder.scala:38)
          at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
          at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
          at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
          at slick.util.SQLBuilder.$anonfun$build$1(SQLBuilder.scala:38)
          at slick.util.SQLBuilder.$anonfun$build$1$adapted(SQLBuilder.scala:36)
          at slick.jdbc.JdbcInvokerComponent$QueryInvokerImpl.setParam(JdbcInvokerComponent.scala:35)
          at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33)
          at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
          at slick.jdbc.Invoker.foreach(Invoker.scala:47)
          at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
          at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
          at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
          at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
          at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:216)
          at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:216)
          at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
          at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at java.lang.Thread.run(Thread.java:748)`

**Comment by tminglei** [comment]
@pantelissd  `jdbcdslog` didn't implement `unwrap(..)` well.
I'll provide a way to allow customizing for this.

**Comment by tminglei** [comment]
Provided a [custom way](https://github.com/tminglei/slick-pg/commit/5c23c6d6789f2cf0373405f0a67ed527cc509bb3#diff-f11443aceadcdb80e9d1dcbffdd5603dR14) for this, 
```scala
  ///---
  protected def useNativeArray: Boolean = true
  ///---
```
you can override it to `useNativeArray = false` in your customized PostgresProfile, to prevent it to use jdbc connection's `createArrayOf`, which will throw the cast exception.

_Pls help check. Thx!_

**Comment by pantelissd** [comment]
@tminglei i cloned the code locally and overwritten `useNativeArray` and it works now. Thanks. Will this be released in an upcoming version or is it release in another SNAPSHOT artifact or something?

**Comment by tminglei** [comment]
Ok. I'll release it ASAP.

**Comment by pantelissd** [comment]
Thank you so much @tminglei !
