### ISSUE TITLE
Large Files support -  Invalid value "interface org.postgresql.PGConnection" for parameter "iface"

### ISSUE THREAD

**Issue by JethroMV** [tminglei/slick-pg#458]
Hi, I'm trying to use slick-pg to use the Large Object Postgresl functionality, but keep getting the following exception, which I do not understand.

```
[info] - must Control Emulations *** FAILED ***
[info]   org.h2.jdbc.JdbcSQLDataException: Invalid value "interface org.postgresql.PGConnection" for parameter "iface" [90008-199]
[info]   at org.h2.message.DbException.getJdbcSQLException(DbException.java:587)
[info]   at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[info]   at org.h2.message.DbException.get(DbException.java:205)
[info]   at org.h2.message.DbException.getInvalidValueException(DbException.java:280)
[info]   at org.h2.jdbc.JdbcConnection.unwrap(JdbcConnection.java:1942)
[info]   at com.zaxxer.hikari.pool.ProxyConnection.unwrap(ProxyConnection.java:455)
[info]   at com.github.tminglei.slickpg.lobj.LargeObjectSupport.$anonfun$buildLargeObjectUploadAction$1(LargeObjectSupport.scala:25)
[info]   at com.github.tminglei.slickpg.lobj.LargeObjectSupport.$anonfun$buildLargeObjectUploadAction$1$adapted(LargeObjectSupport.scala:23)
[info]   at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:70)
[info]   at slick.jdbc.SimpleJdbcAction.run(StreamingInvokerAction.scala:69)
[info]   at slick.dbio.DBIOAction$$anon$1.$anonfun$run$1(DBIOAction.scala:186)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:941)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:941)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info]   at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:186)
[info]   at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:183)
[info]   at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[info]   at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```

The exception is thrown from the following action, taken from . the README [here](https://github.com/tminglei/slick-pg/tree/868f3666197ff3a0a1f233c2a9905feb483551f4/core/src/main/scala/com/github/tminglei/slickpg/lobj). 

```
    val driver = new LargeObjectSupport with ExPostgresProfile {}
    driver.buildLargeObjectUploadAction(inputStream)
```

I have also tried using the `MyPostgresProfile` example profile from the main README, which gives the same exception.

Thanks for any assistance.

**Comment by tminglei** [comment]
@JethroMV are you using H2 driver? But slick-pg used pgjdbc driver's interface (check [here](https://github.com/tminglei/slick-pg/blob/868f366619/core/src/main/scala/com/github/tminglei/slickpg/lobj/LargeObjectSupport.scala#L25) and [here](https://github.com/tminglei/slick-pg/blob/868f366619/core/src/main/scala/com/github/tminglei/slickpg/lobj/LargeObjectStreamingDBIOAction.scala#L28)).
