### ISSUE TITLE
Query using "percentile_disc(fractions) WITHIN GROUP (ORDER BY sort_expression)" generate invalid query for postgresql

### ISSUE THREAD

**Issue by iwanek9ld** [tminglei/slick-pg#656]
Slick version: 3.4.1
Slick-pg version: 0.21.1 (problem existing probably from `v0.17.3`, commit `e64a6e20`)
Postgresql version: 11.10

Postgresql setup:
`docker run --rm -it -e POSTGRES_PASSWORD=password -p 5432:5432 postgres:11.10`

`psql -U postgresl -W -h localhost` and run script.

```
create table t1(f1 float);
insert into t1 values(0.3);
insert into t1 values(0.4);
insert into t1 values(0.5);
insert into t1 values(0.6);
insert into t1 values(0.7);
```

Code example:
```
import com.github.tminglei.slickpg._
import com.github.tminglei.slickpg.agg.PgAggFuncSupport

import scala.concurrent.Await
import scala.concurrent.duration.Duration

trait MyPostgresProfile extends ExPostgresProfile
  with PgArraySupport
  with PgDate2Support
  with PgRangeSupport
  with PgHStoreSupport
  with PgSearchSupport
  with PgNetSupport
  with PgLTreeSupport {

  // Add back `capabilities.insertOrUpdate` to enable native `upsert` support; for postgres 9.5+
  override protected def computeCapabilities: Set[slick.basic.Capability] =
    super.computeCapabilities + slick.jdbc.JdbcCapabilities.insertOrUpdate

  override val api = MyAPI

  object MyAPI extends super.API with ArrayImplicits
    with DateTimeImplicits
    with NetImplicits
    with LTreeImplicits
    with RangeImplicits
    with HStoreImplicits
    with SearchImplicits
    with SearchAssistants {
  }
}

object MyPostgresProfile extends MyPostgresProfile

import MyPostgresProfile.api._

case class Test(field: Double)

class TestTable(tag: Tag) extends Table[Test](tag, None, "t1") {
  def field = column[Double]("f1")

  def * = field <> (Test.apply, Test.unapply)
}

object Hello extends App {
  val db = Database.forURL("jdbc:postgresql://localhost:5432/postgres?user=postgres&password=password", driver = "org.postgresql.Driver")
  val table = TableQuery[TestTable]

  val dbio = table.map { case v => PgAggFuncSupport.OrderedSetAggFunctions.percentileDisc[Double](List(0.5, 0.6)).within(v.field).unnest }.result
  val value = Await.result(db.run(dbio), Duration.Inf)
  println(value)
}
```

Error (output):
```
[error] org.postgresql.util.PSQLException: ERROR: invalid input syntax for type double precision: "{0.5,0.6}"
[error]   Position: 31
[error]         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
[error]         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
[error]         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
[error]         at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
[error]         at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
[error]         at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:41)
[error]         at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:23)
[error]         at slick.jdbc.Invoker.foreach(Invoker.scala:49)
[error]         at slick.jdbc.Invoker.foreach$(Invoker.scala:48)
[error]         at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
[error]         at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
[error]         at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
[error]         at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
[error]         at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$2.run(JdbcActionComponent.scala:214)
[error]         at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[error]         at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:750)
[error] stack trace is suppressed; run last Compile / run for the full output
[error] (Compile / run) org.postgresql.util.PSQLException: ERROR: invalid input syntax for type double precision: "{0.5,0.6}"
[error]   Position: 31
```

Postgres log:
```
2023-07-27 11:11:45.050 UTC [130] ERROR:  invalid input syntax for type double precision: "{0.5,0.6}" at character 31
2023-07-27 11:11:45.050 UTC [130] STATEMENT:  select unnest(percentile_disc('{0.5,0.6}') within group ( order by "f1")) from "t1"
```

**Comment by iwanek9ld** [comment]
Works if you bind query parameter as it is done in testsuite `core/src/test/scala/com/github/tminglei/slickpg/PgAggFuncSupportSuite.scala` with `.bind`:

```
val dbio = table.map { case v => PgAggFuncSupport.OrderedSetAggFunctions.percentileDisc[Double](List(0.5, 0.6).bind).within(v.field).unnest }.result
  v
```
